mod agent;
mod channels;
mod config;
mod containers;
mod db;
mod dto_export;
mod gateway;
mod memory;
mod metrics;
pub mod net;
mod oauth;
mod process_manager;
mod redact;
mod scheduler;
mod secrets;
mod mcp;
mod shutdown;
mod skills;
mod curator;
mod tools;
mod trace_propagation;
mod uploads;

use anyhow::Result;
use std::collections::HashMap;
use std::sync::Arc;
use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt, EnvFilter};

/// Load .env file from binary's directory or current working directory.
/// In production (systemd), env vars come from `EnvironmentFile`.
fn load_env() {
    let mut env_path = std::path::PathBuf::from(".env");

    // Try from binary's directory first (most reliable for production)
    if let Ok(exe_path) = std::env::current_exe()
        && let Some(dir) = exe_path.parent() {
            let p = dir.join(".env");
            if p.exists() {
                env_path = p;
            }
        }

    // Auto-generate .env on first run (OPEX_AUTH_TOKEN and OPEX_MASTER_KEY)
    if !env_path.exists() {
        let mut auth_bytes = [0u8; 32];
        let mut key_bytes = [0u8; 32];
        rand::RngCore::fill_bytes(&mut rand::rng(), &mut auth_bytes);
        rand::RngCore::fill_bytes(&mut rand::rng(), &mut key_bytes);
        let content = format!(
            "# Auto-generated by opex-core on first run\nOPEX_AUTH_TOKEN={}\nOPEX_MASTER_KEY={}\n",
            hex::encode(auth_bytes),
            hex::encode(key_bytes),
        );
        if std::fs::write(&env_path, &content).is_ok() {
            eprintln!("[dotenv] created .env with generated tokens: {}", env_path.display());
        }
    }

    if env_path.exists() {
        if dotenv::from_path(&env_path).is_ok() {
            eprintln!("[dotenv] loaded .env from: {}", env_path.display());
        }
    } else {
        eprintln!("[dotenv] .env not found, using environment variables");
    }
}

/// Tracing layer that broadcasts log entries as JSON to WebSocket clients.
struct BroadcastLogLayer {
    tx: tokio::sync::broadcast::Sender<String>,
}

impl<S: tracing::Subscriber> tracing_subscriber::Layer<S> for BroadcastLogLayer {
    fn on_event(&self, event: &tracing::Event<'_>, _ctx: tracing_subscriber::layer::Context<'_, S>) {
        // Skip all work when no UI clients are subscribed
        if self.tx.receiver_count() == 0 { return; }

        use tracing_subscriber::field::Visit;

        struct Visitor {
            message: String,
        }
        impl Visit for Visitor {
            fn record_debug(&mut self, field: &tracing::field::Field, value: &dyn std::fmt::Debug) {
                if field.name() == "message" {
                    self.message = format!("{value:?}");
                }
            }
        }

        let mut visitor = Visitor { message: String::new() };
        event.record(&mut visitor);

        let level = match *event.metadata().level() {
            tracing::Level::ERROR => "ERROR",
            tracing::Level::WARN => "WARN",
            tracing::Level::INFO => "INFO",
            tracing::Level::DEBUG => "DEBUG",
            tracing::Level::TRACE => "DEBUG",
        };

        let log_event = opex_types::ws::WsEvent::Log {
            level: level.to_string(),
            target: event.metadata().target().to_string(),
            message: visitor.message,
            timestamp: chrono::Utc::now().to_rfc3339(),
        };

        // Best-effort send — drop if no subscribers
        self.tx.send(log_event.to_json()).ok();
    }
}

/// Phase 65 OBS-01 / OBS-02 (Plan 02): live OTel provider handles retained
/// across the lifetime of the process so `main()` can invoke `.shutdown()`
/// on clean exit. OTel 0.31 removed the global `shutdown_tracer_provider()`
/// helper — providers now own their shutdown lifecycle.
#[cfg(feature = "otel")]
static OTEL_PROVIDERS: std::sync::OnceLock<(
    opentelemetry_sdk::trace::SdkTracerProvider,
    opentelemetry_sdk::metrics::SdkMeterProvider,
)> = std::sync::OnceLock::new();

/// Initialize tracing subscriber with optional OTEL layer.
///
/// Phase 65 Plan 02 (OTel 0.31 migration):
///   * `opentelemetry_sdk::trace::TracerProvider` → `SdkTracerProvider`
///   * `opentelemetry_sdk::Resource::new(...)` → `Resource::builder().with_service_name(...).build()`
///   * `SpanExporter::builder().with_tonic()` now requires the `grpc-tonic`
///     feature (enabled at workspace level).
///   * `shutdown_tracer_provider()` removed — caller owns the handle and
///     invokes `.shutdown()` on exit. Handles stored in `OTEL_PROVIDERS`.
///   * Metrics provider now created alongside tracer so Plan 02 OTel
///     instruments (`tool_latency_seconds`, `llm_call_duration_seconds`,
///     `db_query_duration_seconds`, `llm_tokens_total`) are exported via
///     the same OTLP collector endpoint.
fn init_tracing(log_tx: tokio::sync::broadcast::Sender<String>, cfg: &config::AppConfig) {
    let env_filter = EnvFilter::try_from_default_env().unwrap_or_else(|_| "opex_core=info".into());
    let fmt_layer = tracing_subscriber::fmt::layer();
    let broadcast_layer = BroadcastLogLayer { tx: log_tx };

    #[cfg(feature = "otel")]
    {
        use opentelemetry_otlp::WithExportConfig;

        if cfg.otel.enabled {
            let endpoint = std::env::var("OTEL_EXPORTER_OTLP_ENDPOINT")
                .unwrap_or_else(|_| "http://localhost:4317".to_string());
            eprintln!(
                "[otel] exporting traces + metrics to {endpoint} as {:?}",
                cfg.otel.service_name
            );

            // Shared resource: `service.name` identifies this process in the
            // collector. `Resource::builder()` pulls default attributes
            // (service.version via env, telemetry.sdk.*) — the 0.31 idiom.
            let resource = opentelemetry_sdk::Resource::builder()
                .with_service_name(cfg.otel.service_name.clone())
                .build();

            // ── Trace exporter + provider ───────────────────────────────
            let span_exporter = match opentelemetry_otlp::SpanExporter::builder()
                .with_tonic()
                .with_endpoint(&endpoint)
                .build()
            {
                Ok(e) => e,
                Err(err) => {
                    eprintln!("[otel] span exporter build failed: {err}; falling back");
                    tracing_subscriber::registry()
                        .with(env_filter)
                        .with(fmt_layer)
                        .with(broadcast_layer)
                        .init();
                    return;
                }
            };
            // Sampler — `TraceIdRatioBased(ratio)` is *consistent*: the same
            // trace_id either keeps the whole trace or drops the whole trace
            // across every service that shares it. Critical for cross-process
            // correlation — uniform sampling per-service would yield half-
            // sampled traces (Core span kept, Toolgate span dropped) that
            // look broken in Jaeger.
            //
            // Ratio 1.0 (default) → AlwaysOn semantics for compatibility with
            // existing Pi setups. Production-scale should set 0.05–0.2 in
            // opex.toml `[otel] sampling_ratio = 0.1`.
            let ratio = cfg.otel.sampling_ratio.clamp(0.0, 1.0);
            let sampler = opentelemetry_sdk::trace::Sampler::ParentBased(Box::new(
                opentelemetry_sdk::trace::Sampler::TraceIdRatioBased(ratio),
            ));
            eprintln!("[otel] trace sampler: ParentBased(TraceIdRatioBased({ratio}))");
            let tracer_provider = opentelemetry_sdk::trace::SdkTracerProvider::builder()
                .with_batch_exporter(span_exporter)
                .with_resource(resource.clone())
                .with_sampler(sampler)
                .build();
            opentelemetry::global::set_tracer_provider(tracer_provider.clone());

            // Install the W3C TraceContext propagator globally so
            // `trace_propagation::inject_trace_context` can fetch it
            // when stamping outgoing reqwest calls. Without this,
            // `get_text_map_propagator` returns a no-op propagator and
            // cross-process traceparent headers never get written.
            opentelemetry::global::set_text_map_propagator(
                opentelemetry_sdk::propagation::TraceContextPropagator::new(),
            );

            // ── Metric exporter + provider (Plan 02 OBS-02) ─────────────
            let metric_exporter = match opentelemetry_otlp::MetricExporter::builder()
                .with_tonic()
                .with_endpoint(&endpoint)
                .build()
            {
                Ok(e) => e,
                Err(err) => {
                    eprintln!("[otel] metric exporter build failed: {err}; proceeding with traces only");
                    // Keep tracer provider wired; install empty meter
                    // provider so `MetricsRegistry::install_otel_instruments`
                    // fails safe (the underlying global meter is a no-op).
                    let _ = OTEL_PROVIDERS.set((
                        tracer_provider.clone(),
                        opentelemetry_sdk::metrics::SdkMeterProvider::builder().build(),
                    ));
                    let tracer = opentelemetry::trace::TracerProvider::tracer(
                        &tracer_provider,
                        "opex",
                    );
                    let otel_layer = tracing_opentelemetry::layer().with_tracer(tracer);
                    tracing_subscriber::registry()
                        .with(env_filter)
                        .with(fmt_layer)
                        .with(broadcast_layer)
                        .with(otel_layer)
                        .init();
                    return;
                }
            };
            let meter_provider = opentelemetry_sdk::metrics::SdkMeterProvider::builder()
                .with_periodic_exporter(metric_exporter)
                .with_resource(resource)
                .build();
            opentelemetry::global::set_meter_provider(meter_provider.clone());

            // Retain handles for graceful shutdown.
            let _ = OTEL_PROVIDERS.set((tracer_provider.clone(), meter_provider));

            let tracer = opentelemetry::trace::TracerProvider::tracer(&tracer_provider, "opex");
            let otel_layer = tracing_opentelemetry::layer().with_tracer(tracer);

            tracing_subscriber::registry()
                .with(env_filter)
                .with(fmt_layer)
                .with(broadcast_layer)
                .with(otel_layer)
                .init();
            return;
        }
    }

    #[cfg(not(feature = "otel"))]
    let _ = &cfg.otel; // suppress unused warning

    tracing_subscriber::registry()
        .with(env_filter)
        .with(fmt_layer)
        .with(broadcast_layer)
        .init();
}

#[tokio::main(worker_threads = 4)]
async fn main() -> Result<()> {
    // Load .env file (no-op if not found - env vars may come from systemd EnvironmentFile)
    load_env();

    // Load config BEFORE tracing init (OTEL layer depends on config)
    let cfg = config::AppConfig::load(opex_gateway_util::config_path::resolve_config_path())?;

    // Broadcast channel for real-time log streaming (created before tracing init)
    let (log_tx, _) = tokio::sync::broadcast::channel::<String>(256);

    // Structured logging with broadcast layer for UI + optional OTEL
    init_tracing(log_tx.clone(), &cfg);

    tracing::info!(listen = %cfg.gateway.listen, "OPEX Core starting...");

    // Multi-agent timeout invariant: warn (don't reject) on config that lets
    // the outer safety net fire before the inner sync deadlines.
    cfg.agent_tool.warn_if_invariant_violated();

    // systemd unit installation is handled by setup.sh (see "Systemd service"
    // stage). Core no longer writes unit files at runtime — that was a
    // hot-path side effect that belonged to the installer.

    // Model metadata catalog (context windows from models.dev/…): background
    // load + refresh into the process-global catalog. No-op when disabled.
    // The SSRF-guarded client is built here (host policy) and handed to the crate.
    {
        let mc = &cfg.model_catalog;
        opex_catalog::service::spawn(
            opex_catalog::service::CatalogConfig {
                enabled: mc.enabled,
                refresh_hours: mc.refresh_hours,
                models_dev_url: mc.models_dev_url.clone(),
                openrouter_url: mc.openrouter_url.clone(),
            },
            crate::net::ssrf::ssrf_http_client(std::time::Duration::from_secs(20)),
        );
    }

    // Config hot-reload watcher
    let shared_config = std::sync::Arc::new(tokio::sync::RwLock::new(cfg.clone()));
    let config_api_write_flag = std::sync::Arc::new(std::sync::atomic::AtomicBool::new(false));
    // CancellationToken for the OS-thread watchers is created now so they can be
    // cancelled at the bottom of main alongside the tokio bg_shutdown token (Bug 13).
    let watcher_cancel = tokio_util::sync::CancellationToken::new();
    config::spawn_config_watcher(
        opex_gateway_util::config_path::resolve_config_path(),
        shared_config.clone(),
        config_api_write_flag.clone(),
        watcher_cancel.clone(),
    );

    // Database pool — DATABASE_URL env var overrides opex.toml value
    let db_url = std::env::var("DATABASE_URL").unwrap_or_else(|_| cfg.database.url.clone());
    let db_pool = db::create_pool(&db_url).await?;
    tracing::info!("database connected, running migrations...");
    sqlx::migrate::Migrator::new(std::path::Path::new("migrations"))
        .await?
        .run(&db_pool)
        .await?;
    tracing::info!("migrations complete");

    // Startup cleanup: repair sessions interrupted by previous crash (batched)
    cleanup_interrupted_sessions(&db_pool).await;

    // Startup cleanup: delete orphaned tool-result rows whose parent assistant
    // row was lost to a crash (the DB counterpart of the read-path filter, so
    // they don't accumulate). Best-effort — a failure here must not block boot.
    match crate::db::sessions::sweep_orphan_tool_results(&db_pool).await {
        Ok(0) => {}
        Ok(n) => tracing::info!(deleted = n, "swept orphaned tool-result rows"),
        Err(e) => tracing::warn!(error = %e, "orphan tool-result sweep failed (non-fatal)"),
    }

    // Secrets vault
    let master_key_hex = get_master_key();
    let secrets_manager = secrets::SecretsManager::new(&master_key_hex, db_pool.clone())?;
    let secrets_count = secrets_manager.load_all().await?;

    // One-time migration: move channel credentials from JSONB to encrypted vault.
    // Idempotent — safe to run every startup.
    gateway::migrate_credentials_to_vault(&db_pool, &secrets_manager).await;
    // One-time migration: copy provider keys from legacy vault patterns into unified PROVIDER_CREDENTIALS.
    gateway::migrate_provider_keys_to_vault(&db_pool, &secrets_manager).await;
    // One-time migration: move OAuth tokens/credentials from old per-agent format to per-account vault.
    if let Err(e) = crate::oauth::migrate_oauth_vault(&db_pool, &secrets_manager).await {
        tracing::error!(error = %e, "OAuth vault migration failed — old tokens may not be available");
    }

    // One-time migration: sign historical /uploads/* URLs in messages (v0.26.0).
    {
        let upload_key = secrets_manager.get_upload_hmac_key();
        match db::upload_migration::run_upload_signature_migration(
            &db_pool,
            &upload_key,
        )
        .await
        {
            Ok(n) if n > 0 => tracing::info!(rows = n, "upload signature migration complete"),
            Ok(_) => {}
            Err(e) => tracing::error!(
                err = %e,
                "upload signature migration failed — continuing"
            ),
        }
    }

    // One-time migration: seed provider profiles (Default + per-agent), rewrite
    // agent TOMLs and clear the migrated capabilities from provider_active
    // (m084). Idempotent via sys_flags['profiles_seed_v1']; re-runs on failure.
    if let Err(e) =
        db::profile_migration::run_profiles_seed(&db_pool, std::path::Path::new("config/agents"))
            .await
    {
        tracing::error!(error = %e, "profiles seed failed; will retry on next startup");
    }

    // No hardcoded secrets — user creates all secrets via UI.
    // Channel-specific secrets (bot tokens) are auto-seeded when agents are created.
    // OPEX_AUTH_TOKEN and OPEX_MASTER_KEY stay in .env only (bootstrap).

    let secrets_manager = Arc::new(secrets_manager);
    tracing::info!(count = secrets_count, "secrets vault loaded");

    // Memory store (embedding via toolgate proxy)
    let toolgate_url = cfg.toolgate_url.clone().unwrap_or_else(|| "http://localhost:9011".to_string());
    let effective_toolgate_url = if cfg.memory.enabled { &toolgate_url } else { "" };
    let embedder: Arc<dyn memory::EmbeddingService> = Arc::new(memory::ToolgateEmbedder::new(
        db_pool.clone(),
        effective_toolgate_url,
        cfg.memory.embed_dim.unwrap_or(0),
        cfg.memory.embed_dimensions.unwrap_or(0),
    ));
    // P0.1 CRITICAL: sync persistent `memory.dim_mismatch` flag from
    // system_flags BEFORE binding the HTTP listener. Without this eager
    // init, the first POST /api/memory after restart sees the in-memory
    // `AtomicBool::new(false)` default and bypasses the dim-mismatch guard,
    // letting a new-dim vector land in a table full of old-dim chunks and
    // corrupting the HNSW index. Probe / dim detection also happens here
    // so subsequent index() calls don't pay the latency on first request.
    embedder.ensure_initialized().await;
    // FTS language resolution order: TOML override → persisted DB value → "simple" placeholder
    // (auto-detect runs later after agent_configs is loaded). Persisted value comes
    // from `system_flags` so PUT /api/memory/fts-language survives restarts.
    let fts_lang = if let Some(toml_lang) = cfg.memory.fts_language.clone() {
        toml_lang
    } else {
        opex_db::sys_flags::get(&db_pool, "memory.fts_language")
            .await
            .and_then(|v| v.as_str().map(String::from))
            .unwrap_or_else(|| "simple".to_string())
    };
    let memory_store = Arc::new(memory::MemoryStore::new(db_pool.clone(), embedder.clone(), fts_lang));
    if embedder.is_available() {
        tracing::info!("embedding configured — will initialize on first memory operation");
        // Watch workspace files for auto-reindexing
        memory::spawn_workspace_watcher(
            config::WORKSPACE_DIR.to_string(),
            memory_store.clone(),
            tokio::runtime::Handle::current(),
            watcher_cancel.clone(),
        );
        // First-run bootstrap: the watcher only handles file CHANGE events, so
        // a fresh install with workspace files already on disk would have zero
        // shared chunks until someone manually triggers `memory.reindex`. If
        // we see no shared chunks at all, enqueue a one-shot reindex task —
        // the memory worker picks it up and indexes the workspace (idempotent
        // via DELETE-by-source + INSERT). Subsequent restarts skip the check.
        //
        // Run in a background task that waits for toolgate (managed child
        // process spawned later in main) to come up. Without this delay the
        // worker would dequeue immediately and fail every embedding call with
        // a connection error, marking the task as 'done' with 0 indexed.
        let bootstrap_pool = db_pool.clone();
        let bootstrap_toolgate_url = toolgate_url.clone();
        tokio::spawn(async move {
            // Wait up to 90s for toolgate to be ready (POST /health 200).
            let http = reqwest::Client::builder()
                .timeout(std::time::Duration::from_secs(3))
                .build()
                .expect("reqwest client build");
            let health_url = format!(
                "{}/health",
                bootstrap_toolgate_url.trim_end_matches('/')
            );
            let mut ready = false;
            for attempt in 1..=18 {
                tokio::time::sleep(std::time::Duration::from_secs(5)).await;
                if http.get(&health_url).send().await.is_ok_and(|r| r.status().is_success()) {
                    tracing::info!(attempt, "memory bootstrap: toolgate ready");
                    ready = true;
                    break;
                }
            }
            if !ready {
                tracing::warn!(
                    "memory bootstrap: toolgate not reachable after 90s — skipping reindex enqueue"
                );
                return;
            }

            let has_shared: bool = match sqlx::query_scalar::<_, bool>(
                "SELECT EXISTS(SELECT 1 FROM memory_chunks WHERE scope = 'shared')",
            )
            .fetch_one(&bootstrap_pool)
            .await
            {
                Ok(v) => {
                    tracing::info!(has_shared = v, "memory bootstrap check");
                    v
                }
                Err(e) => {
                    tracing::warn!(
                        error = %e,
                        "memory bootstrap probe failed — assuming no shared chunks (will attempt reindex)"
                    );
                    false
                }
            };
            if !has_shared {
                match db::memory_queries::enqueue_reindex_task(
                    &bootstrap_pool,
                    serde_json::json!({"agent_id": "", "include_sessions": false}),
                )
                .await
                {
                    Ok(task_id) => tracing::info!(
                        %task_id,
                        "no shared chunks — enqueued initial workspace reindex"
                    ),
                    Err(e) => tracing::warn!(
                        error = %e,
                        "failed to enqueue initial workspace reindex"
                    ),
                }
            }
        });
    } else {
        tracing::info!("embedding not configured — memory features disabled");
    }

    // Shutdown token: cancelled once axum::serve returns (i.e. after SIGTERM/Ctrl-C).
    // Background tasks select on this token so they exit promptly instead of
    // completing their current DB-query round-trip first (Bug 24).
    // Created here (before init_container_manager) so the idle-reaper task (Bug 14)
    // can select on it from the moment it is spawned.
    let bg_shutdown = tokio_util::sync::CancellationToken::new();

    // Tool registry — load service endpoints from workspace/tools/*.yaml
    let tool_registry = init_tool_registry().await;

    // Container Manager (Docker lifecycle for on-demand MCP servers)
    let container_manager = init_container_manager(bg_shutdown.clone()).await;

    // MCP registry (MCP tool discovery from MCP containers)
    let mcp_registry = init_mcp_registry(container_manager.clone()).await;

    // Load agent configs — no default agent created; Setup Wizard handles first agent
    std::fs::create_dir_all("config/agents")?;
    let agent_configs = config::load_agent_configs("config/agents")?;
    if agent_configs.is_empty() {
        tracing::info!("no agent configs found — Setup Wizard will create the first agent");
    }
    tracing::info!(agents = agent_configs.len(), "agent configs loaded");

    // Auto-detect FTS language from first agent's language ONLY when neither
    // TOML override nor persisted DB value is present (i.e. memory_store is
    // currently using the "simple" placeholder). On detect, persist to DB so
    // future restarts skip the agent-order-dependent detection.
    if cfg.memory.fts_language.is_none()
        && memory_store.fts_language() == "simple"
        && let Some(first) = agent_configs.first() {
            let detected = memory::admin::detect_fts_language(&first.agent.language);
            tracing::info!(
                agent = %first.agent.name,
                agent_lang = %first.agent.language,
                fts_lang = %detected,
                "auto-detected FTS language from first agent"
            );
            memory_store.set_fts_language(&detected);
            if let Err(e) = opex_db::sys_flags::upsert(
                &db_pool,
                "memory.fts_language",
                serde_json::Value::String(detected.clone()),
            )
            .await
            {
                tracing::warn!(error = %e, "failed to persist auto-detected FTS language");
            }
        }

    // UI event broadcast channel (shared between scheduler and WS handler)
    let (ui_event_tx, _) = tokio::sync::broadcast::channel::<String>(512);

    // Scheduler
    let sched = Arc::new(scheduler::Scheduler::new(ui_event_tx.clone()).await?);

    // Extract shared URLs from service configs
    let service_map = tools::service_registry::load_service_map(config::WORKSPACE_DIR).await;
    let toolgate_url = cfg.toolgate_url.clone()
        .or_else(|| service_map.get("toolgate").map(|t| t.url.clone()));

    // Code execution sandbox (optional — requires Docker + sandbox.enabled = true)
    let tool_embed_cache = Arc::new(tools::embedding::ToolEmbeddingCache::new());

    let docker_url = std::env::var("DOCKER_HOST")
        .unwrap_or_else(|_| "unix:///var/run/docker.sock".to_string());

    let sandbox = if cfg.sandbox.enabled {
        match containers::sandbox::CodeSandbox::new(&docker_url, &cfg.sandbox) {
            Ok(s) => {
                tracing::info!(
                    image = %cfg.sandbox.image,
                    timeout = cfg.sandbox.timeout_secs,
                    "code execution sandbox initialized"
                );
                Some(Arc::new(s))
            }
            Err(e) => {
                tracing::warn!(error = %e, "failed to initialize sandbox, code_exec disabled");
                None
            }
        }
    } else {
        tracing::info!("sandbox disabled (sandbox.enabled = false)");
        None
    };

    // Shared agent dependencies (for hot-starting agents from API)
    let penalty_cache = Arc::new(crate::db::tool_quality::PenaltyCache::new(db_pool.clone()));

    let audit_queue = Arc::new(crate::db::audit_queue::AuditQueue::new(db_pool.clone()));

    let tool_exec_ctx = Arc::new(crate::tools::yaml_tools::ToolExecutionContext::new(
        cfg.tools_cache.max_entries,
    ));

    let checkpoint_mgr = Arc::new(crate::agent::checkpoint_manager::CheckpointManager::new(
        cfg.checkpoint.clone(),
    ));

    // Process-wide provider cooldown registry (Session Resilience Task 4 /
    // WS4) — one instance shared by every agent for the life of the process.
    let cooldowns = Arc::new(crate::agent::provider_cooldown::ProviderCooldowns::new());

    crate::agent::workspace::set_shared_writable_dirs(cfg.agent_tool.shared_writable_dirs.clone());

    crate::agent::lsp::set_lsp_enabled(cfg.lsp.enabled);
    let lsp_manager: Option<Arc<crate::agent::lsp::LspManager>> = if cfg.lsp.enabled {
        use std::time::Duration;
        let mgr = crate::agent::lsp::LspManager::with_host_factory(
            Duration::from_secs(cfg.lsp.request_timeout_secs),
            Duration::from_secs(cfg.lsp.idle_timeout_secs),
            Duration::from_secs(cfg.lsp.broken_ttl_secs),
            cfg.lsp.max_servers_per_agent,
        );
        mgr.clone().spawn_sweeper();
        tracing::info!(
            request_timeout_secs = cfg.lsp.request_timeout_secs,
            idle_timeout_secs    = cfg.lsp.idle_timeout_secs,
            broken_ttl_secs      = cfg.lsp.broken_ttl_secs,
            max_servers_per_agent = cfg.lsp.max_servers_per_agent,
            "LSP manager initialized"
        );
        Some(mgr)
    } else {
        tracing::info!("LSP orchestration disabled (lsp.enabled = false)");
        None
    };

    // Resolve a concrete toolgate URL String for the handler registry BEFORE the
    // `Option<String>` `toolgate_url` (bound above) is moved into AgentDeps.
    let toolgate_url_for_handlers = toolgate_url
        .clone()
        .unwrap_or_else(|| "http://localhost:9011".to_string());

    let agent_deps = Arc::new(tokio::sync::RwLock::new(gateway::AgentDeps {
        mcp: mcp_registry.clone(),
        workspace_dir: config::WORKSPACE_DIR.to_string(),
        toolgate_url,
        sandbox: sandbox.clone(),
        tool_embed_cache,
        penalty_cache: penalty_cache.clone(),
        audit_queue,
        tool_exec_ctx,
        checkpoint_mgr,
        lsp_manager,
        cooldowns,
    }));

    let agents_map: gateway::AgentMap = Arc::new(tokio::sync::RwLock::new(HashMap::new()));
    let guards_map: gateway::AccessGuardMap = Arc::new(tokio::sync::RwLock::new(HashMap::new()));

    // Stream registry for SSE resume support
    let stream_registry = Arc::new(gateway::stream_registry::StreamRegistry::new(db_pool.clone()));

    // Managed process manager (channels, toolgate — native child processes)
    let base_dir = std::env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from("."));
    let process_manager: Option<Arc<process_manager::ProcessManager>> = if cfg.managed_process.is_empty() {
        None
    } else {
        let pm = Arc::new(process_manager::ProcessManager::new(cfg.managed_process.clone(), base_dir));
        tracing::info!(count = cfg.managed_process.len(), "managed process manager initialized");
        Some(pm)
    };

    // OAuth manager
    let public_url = cfg.gateway.public_url.clone().unwrap_or_else(|| {
        // Extract port from listen address (e.g. "0.0.0.0:18789" → 18789)
        let port = cfg.gateway.listen.rsplit(':').next().unwrap_or("18789");
        format!("http://localhost:{port}")
    });
    // OAuth talks to provider token endpoints whose URLs are *currently*
    // hard-coded in `oauth::PROVIDERS`, but the architecture is set up to
    // allow custom providers in the future. Use the SSRF-safe client so that
    // a future addition cannot accidentally point Core at a private-IP
    // host (audit 2026-05-08, defence-in-depth).
    let oauth_manager = Arc::new(crate::oauth::OAuthManager::new(
        db_pool.clone(),
        secrets_manager.clone(),
        crate::net::ssrf::ssrf_http_client(std::time::Duration::from_secs(30)),
        public_url,
    ));

    // Phase 62 RES-02: single process-wide metrics registry. Shared via
    // `InfraServices.metrics` so SSE coalescer (Plan 03) and
    // `/api/health/dashboard` handler (Plan 02) see the same counters.
    let metrics = Arc::new(crate::metrics::MetricsRegistry::new());

    // Publish to the process-wide OnceLock so `RoutingProvider::handle_provider_error`
    // (which has no `AppState` in scope) bumps the same counters as the dashboard.
    crate::metrics::install_global(metrics.clone());

    // Phase 65 Plan 02 OBS-02: when --features otel is on, wire OTel
    // instruments onto the registry. Safe to call unconditionally — the
    // method is itself feature-gated and `install_otel_instruments()` is a
    // no-op if the global MeterProvider was not set by init_tracing (e.g.
    // when `cfg.otel.enabled = false`). Idempotent via `OnceLock::set`.
    #[cfg(feature = "otel")]
    metrics.install_otel_instruments();

    let bg_tasks = Arc::new(tokio_util::task::TaskTracker::new());

    // Shared application state for gateway (built early so start_agent_from_config can use it)
    let state = gateway::AppState {
        agents: gateway::clusters::AgentCore::new(
            agents_map.clone(),
            agent_deps,
            Arc::new(tokio::sync::RwLock::new(std::collections::HashMap::new())),
            Arc::new(dashmap::DashMap::new()),
            tool_registry.clone(),
            sched.clone(),
        ),
        auth: gateway::clusters::AuthServices::new(
            secrets_manager.clone(),
            guards_map.clone(),
            oauth_manager,
            Arc::new(tokio::sync::Mutex::new(std::collections::HashMap::new())),
        ),
        infra: gateway::clusters::InfraServices::new(
            db_pool.clone(),
            memory_store,
            embedder.clone(),
            container_manager.clone(),
            sandbox.clone(),
            process_manager.clone(),
            metrics.clone(),
            secrets_manager.clone(),
            bg_tasks.clone(),
        ),
        channels: gateway::clusters::ChannelBus::new(
            Arc::new(tokio::sync::RwLock::new(Vec::new())),
            log_tx.clone(),
            ui_event_tx.clone(),
            stream_registry.clone(),
            bg_tasks.clone(),
        ),
        config: gateway::clusters::ConfigServices::new(
            cfg.clone(),
            shared_config.clone(),
            Arc::new(tokio::sync::Mutex::new(())),
            config_api_write_flag.clone(),
        ),
        status: gateway::clusters::StatusMonitor::new(
            Arc::new(std::sync::RwLock::new(std::collections::HashMap::new())),
            Arc::new(crate::gateway::state::PollingDiagnostics::new()),
            Arc::new(tokio::sync::RwLock::new(None)),
            std::time::Instant::now(),
        ),
        handlers: crate::agent::handler_registry::HandlerRegistry::new(
            toolgate_url_for_handlers,
            reqwest::Client::builder()
                .timeout(std::time::Duration::from_secs(10))
                .build()
                .unwrap_or_else(|_| reqwest::Client::new()),
        ),
    };

    // Managed processes started after TcpListener::bind below — toolgate needs Core API ready.

    // Spawn periodic background tasks (cleanup, watchdog, etc.)
    spawn_background_tasks(&state, process_manager.clone(), &agent_configs, bg_shutdown.clone()).await;

    // Start all agents from config
    start_configured_agents(&state, &agent_configs).await;

    // Load dynamic cron jobs and schedule periodic system jobs
    schedule_periodic_jobs(&state, &agent_configs).await?;

    // Background task: renew expiring Gmail watches every 6 hours
    {
        let renewal_db = db_pool.clone();
        let renewal_oauth = state.auth.oauth.clone();
        tokio::spawn(async move {
            let mut interval = tokio::time::interval(std::time::Duration::from_secs(6 * 3600));
            loop {
                interval.tick().await;
                crate::gateway::renew_expiring_gmail_watches(&renewal_db, &renewal_oauth).await;
            }
        });
    }

    // Start gateway (blocks until shutdown signal)
    let listener = tokio::net::TcpListener::bind(&cfg.gateway.listen).await?;
    tracing::info!(addr = %cfg.gateway.listen, "gateway listening");

    // Durable re-drive of crashed autonomous cron goals — detached AFTER bind so
    // a hung provider can never block the listener (R-LOOP-class outage). The
    // startup sweep above (cleanup_interrupted_sessions) has already repaired the
    // transcripts these drivers will replay.
    {
        let resume_state = state.clone();
        let resume_db = db_pool.clone();
        tokio::spawn(async move {
            resume_autonomous_goals(resume_state, resume_db).await;
        });
        // Sibling sweep: interactive `/goal` sessions are never auto-redriven —
        // their owners are notified to `/goal resume` instead (disjoint by origin).
        let notify_state = state.clone();
        let notify_db = db_pool.clone();
        tokio::spawn(async move {
            notify_interrupted_interactive_goals(notify_state, notify_db).await;
        });
    }

    // ── mDNS: advertise _opex._tcp.local. ──
    let _mdns_daemon = setup_mdns(&cfg);

    // Tailscale Funnel setup
    setup_tailscale(&cfg).await;

    // Notify systemd: service is ready (no-op on non-Linux)
    #[cfg(target_os = "linux")]
    setup_linux_service_notify();

    // SIGHUP: hot-restart agents (Unix only)
    #[cfg(unix)]
    setup_sighup_handler(state.clone());

    // Start managed child processes just before serve
    if let Some(ref pm) = process_manager {
        let pm_clone = pm.clone();
        tokio::spawn(async move {
            tokio::time::sleep(std::time::Duration::from_millis(500)).await;
            pm_clone.start_all().await;
        });
    }

    let shutdown_bg_tasks = state.channels.bg_tasks.clone();
    axum::serve(listener, gateway::router(state)?.into_make_service_with_connect_info::<std::net::SocketAddr>())
        .with_graceful_shutdown(shutdown_signal(cfg.shutdown.drain_timeout_secs + 20))
        .await?;

    // Signal background tasks to stop. They select on bg_shutdown.cancelled()
    // at the top of each iteration so they exit within one tick instead of
    // waiting for the current DB query to finish (Bug 24 fix).
    bg_shutdown.cancel();

    // Signal OS-thread watchers (workspace + config) to exit (Bug 12 / Bug 13).
    watcher_cancel.cancel();

    // ── Graceful shutdown: cancel → drain → stop ──────────────────────────
    // Phase 62 RES-05: extracted into `shutdown::drain_agents_with_scheduler`.
    // Fixes v0.18.0 lock-during-drain bug (read lock held across wait_drain
    // await). Drain timeout is configurable via [shutdown] drain_timeout_secs
    // in opex.toml (default 30s); systemd TimeoutStopSec should be
    // drain_timeout_secs + 10s buffer (40s) so SIGKILL never races the drain.
    let drain_timeout = std::time::Duration::from_secs(cfg.shutdown.drain_timeout_secs);
    crate::shutdown::drain_agents_with_scheduler(
        agents_map.clone(),
        drain_timeout,
        &sched,
    ).await;

    // Session Resilience Task 2 (G1): the drain above cancels every in-flight
    // turn cooperatively and waits up to `drain_timeout`, but a turn that
    // ignores cancellation (wedged tool call, sync block, unresponsive
    // provider) is NOT hard-aborted here — `AgentHandle::shutdown` only tears
    // down subagents/scheduler jobs. Without this sweep such a session would
    // stay `run_status='running'` until either a future restart's
    // `cleanup_interrupted_sessions` (reason "crash_recovery") or the
    // in-process watchdog (which already stopped ticking — it selects on the
    // same shutdown token) eventually notices it. Pre-mark explicitly now, in
    // the ORIGINAL process, with an honest "shutdown" reason. Idempotent — a
    // session the drain already resolved is no longer 'running' and is
    // simply not selected.
    match crate::db::sessions::mark_all_running_sessions_terminated(&db_pool, "shutdown").await {
        Ok(0) => {}
        Ok(n) => tracing::warn!(count = n, "graceful shutdown: pre-marked stragglers interrupted"),
        Err(e) => tracing::error!(error = %e, "graceful shutdown: failed to sweep running sessions"),
    }

    // Drain background tasks spawned by finalize (notifications, knowledge extraction).
    // close() prevents new spawns; timeout prevents hanging on unresponsive DB.
    shutdown_bg_tasks.close();
    let _ = tokio::time::timeout(
        std::time::Duration::from_secs(5),
        shutdown_bg_tasks.wait(),
    ).await;

    tracing::info!("graceful shutdown: stopping managed processes");
    if let Some(pm) = &process_manager { pm.stop_all().await; }

    #[cfg(target_os = "linux")]
    let _ = sd_notify::notify(false, &[sd_notify::NotifyState::Stopping]);

    // Phase 65 OBS-01 (Plan 02): OTel 0.31 removed the global
    // `shutdown_tracer_provider()` helper — each provider owns its own
    // shutdown. Invoke both the tracer and the metric provider so any
    // in-flight OTLP batches are flushed before the process exits.
    #[cfg(feature = "otel")]
    if cfg.otel.enabled
        && let Some((tracer_provider, meter_provider)) = OTEL_PROVIDERS.get()
    {
        if let Err(err) = tracer_provider.shutdown() {
            tracing::warn!(error = %err, "otel tracer provider shutdown failed");
        }
        if let Err(err) = meter_provider.shutdown() {
            tracing::warn!(error = %err, "otel meter provider shutdown failed");
        }
    }

    tracing::info!("OPEX Core shutting down");
    Ok(())
}

/// Notify UI of a watchdog-triggered session timeout. Best-effort —
/// failure to notify is logged but never propagates.
async fn notify_session_timeout(
    db: &sqlx::PgPool,
    ui_tx: &tokio::sync::broadcast::Sender<String>,
    agent_id: &str,
    session_id: uuid::Uuid,
    idle_secs: i64,
) {
    let _ = crate::gateway::notify(
        db,
        ui_tx,
        "agent_error",
        "Session timeout",
        &format!("Agent {agent_id} session was killed after {idle_secs}s of inactivity"),
        serde_json::json!({
            "agent": agent_id,
            "session_id": session_id.to_string(),
            "kind": "session_timeout",
            "idle_secs": idle_secs,
        }),
    ).await;
}

/// Repair sessions interrupted by previous crash (batched loop).
async fn cleanup_interrupted_sessions(db_pool: &sqlx::PgPool) {
    loop {
        match crate::db::sessions::cleanup_interrupted_sessions(db_pool).await {
            Ok(0) => {
                tracing::info!("startup cleanup: no more interrupted sessions");
                break;
            }
            Ok(cleaned) => {
                tracing::info!(cleaned, "cleanup batch completed, checking for more");
            }
            Err(e) => {
                tracing::error!(error = %e, "startup cleanup failed (non-fatal)");
                break;
            }
        }
    }
}

/// Durable re-drive of crashed autonomous (cron AND initiative) goal runs
/// (durable-resumption Phase 1, extended by Phase 2A Task 7 to cover
/// self-initiated goals). MUST run detached AFTER the listener binds so a
/// hung provider can never wedge the gateway bind (the R-LOOP outage class).
/// For each crashed `origin IN ('cron','initiative')` goal it resolves the
/// owning engine, atomically claims it (`interrupted → running` + retry
/// budget via `claim_redrive`), sets a backoff gate, and spawns the goal
/// driver — with the `GoalTarget` resolved from agent CONFIG owner_id for
/// `origin='initiative'` goals (mirrors `approve_proposal`) so re-driven
/// initiative goals keep delivering to their owner, and left `None` for
/// `origin='cron'` goals (ui_event delivery, unchanged). Interactive `/goal`
/// runs (`origin='goal'`) are never selected — `list_redrivable` enforces
/// that scope boundary.
async fn resume_autonomous_goals(state: gateway::AppState, db: sqlx::PgPool) {
    const STALENESS_SECS: i64 = 6 * 3600;
    const MAX_RETRIES: i32 = 3;
    const MAX_PER_BOOT: usize = 5;

    if opex_gateway_util::env::env_var("DISABLE_REDRIVE").is_some() {
        tracing::info!("autonomous goal re-drive disabled via OPEX_DISABLE_REDRIVE");
        return;
    }

    let metrics = state.infra.metrics.clone();
    let redrivable = match crate::db::session_goals::list_redrivable(&db, STALENESS_SECS, MAX_RETRIES).await {
        Ok(r) => r,
        Err(e) => {
            tracing::warn!(error = %e, "resume_autonomous_goals: list_redrivable failed");
            metrics.record_redrive_event("-", "cron_redrive_list_failed");
            return;
        }
    };
    if redrivable.is_empty() {
        return;
    }
    let total = redrivable.len();
    if total > MAX_PER_BOOT {
        tracing::warn!(
            total,
            cap = MAX_PER_BOOT,
            "more crashed cron goals than the per-boot cap; the remainder re-drive on a later boot"
        );
    }
    tracing::info!(total, "resuming crashed autonomous cron goals");

    let mut started = 0usize;
    for rg in redrivable.into_iter().take(MAX_PER_BOOT) {
        let Some(engine) = state.agents.get_engine(&rg.agent_id).await else {
            tracing::warn!(session = %rg.session_id, agent = %rg.agent_id, "re-drive: agent engine not resolvable, skipping");
            continue;
        };
        let Some(pool) = engine.cfg().goal_pool.clone() else {
            continue;
        };
        if crate::agent::goal::pool::is_running(&pool, rg.session_id) {
            metrics.record_redrive_event(&rg.agent_id, "cron_redrive_skipped_live");
            continue; // a live driver already owns this session
        }
        match crate::db::sessions::claim_redrive(&db, rg.session_id, MAX_RETRIES).await {
            Ok(Some(retry)) => {
                // Exponential backoff so a crash-looping goal is not retried on every boot.
                let backoff_secs = 60i64.saturating_mul(1i64 << (retry.clamp(0, 8) as u32));
                if let Err(e) = crate::db::session_goals::set_next_redrive_at(&db, rg.session_id, backoff_secs).await {
                    tracing::warn!(session = %rg.session_id, error = %e, "re-drive: set_next_redrive_at failed");
                }
                // origin='cron' → GoalTarget None (ui_event delivery, unchanged). origin='initiative'
                // → resolve the owner DM target from agent CONFIG owner_id (H1: never the request),
                // mirroring `approve_proposal`'s spawn so a re-driven initiative goal still delivers
                // its proposal/results to the owner instead of silently continuing headless.
                let target = if rg.origin == "initiative" {
                    let owner = engine.cfg().agent.access.as_ref().and_then(|a| a.owner_id.clone());
                    crate::agent::initiative::delivery::resolve_owner_target(&db, &rg.agent_id, owner.as_deref()).await
                } else {
                    None
                };
                // Reset the persisted decompose-fallback flag on redrive — the pre-refactor
                // in-memory flag reset on every driver spawn; a crash-redriven initiative goal
                // must be able to retry decompose, not stay permanently flat.
                let _ = crate::db::session_goals::set_decompose_failed(&db, rg.session_id, false).await;
                let handle = crate::agent::goal::driver::spawn_goal_driver(engine.clone(), rg.session_id, target);
                pool.insert(rg.session_id, handle);
                started += 1;
                metrics.record_redrive_event(&rg.agent_id, "cron_redrive_started");
                tracing::info!(session = %rg.session_id, agent = %rg.agent_id, retry, "autonomous goal re-drive started");
            }
            Ok(None) => {
                metrics.record_redrive_event(&rg.agent_id, "cron_redrive_claim_raced");
                tracing::debug!(session = %rg.session_id, "re-drive: claim skipped (raced or budget exhausted)");
            }
            Err(e) => {
                metrics.record_redrive_event(&rg.agent_id, "cron_redrive_claim_failed");
                tracing::warn!(session = %rg.session_id, error = %e, "re-drive: claim_redrive failed");
            }
        }
    }
    tracing::info!(started, "autonomous goal re-drive sweep complete");
}

/// Notify owners of interactive (`/goal`) sessions whose autonomous driver was
/// lost to a restart. Unlike cron goals these are NEVER auto-redriven — doing so
/// would silently continue a human's live chat (`list_redrivable` enforces the
/// `origin='cron'` boundary). Instead the owner gets a notification prompting
/// `/goal resume`, and the goal is paused so it is not re-notified next boot and
/// lands in the state `/goal resume` reactivates.
async fn notify_interrupted_interactive_goals(state: gateway::AppState, db: sqlx::PgPool) {
    const STALENESS_SECS: i64 = 6 * 3600;

    let goals = match crate::db::session_goals::list_interrupted_interactive_goals(&db, STALENESS_SECS).await {
        Ok(g) => g,
        Err(e) => {
            tracing::warn!(error = %e, "notify_interrupted_interactive_goals: list failed");
            return;
        }
    };
    if goals.is_empty() {
        return;
    }
    let ui_event_tx = &state.channels.ui_event_tx;
    let mut notified = 0usize;
    for g in &goals {
        let snippet: String = g.goal_text.chars().take(80).collect();
        let body = format!("Your goal \"{snippet}\" was interrupted by a restart. Send /goal resume to continue.");
        let data = serde_json::json!({
            "sessionId": g.session_id.to_string(),
            "agentId": g.agent_id,
            "userId": g.user_id,
        });
        if let Err(e) = crate::gateway::notify(
            &db, ui_event_tx, "goal_interrupted", "Goal interrupted", &body, data,
        ).await {
            // Leave status='active' so a later boot retries the notification.
            tracing::warn!(session = %g.session_id, error = %e, "goal-interrupted notify failed");
            continue;
        }
        // Best-effort channel-push (e.g. Telegram) when the session has a persisted
        // chat_id. The UI bell above is the reliable path; at early boot the channel
        // adapter may not be connected yet, so a push failure only logs.
        if let Some(chat_id) = g.chat_id
            && let Some(engine) = state.agents.get_engine(&g.agent_id).await
        {
            let cctx = crate::agent::pipeline::CommandContext {
                cfg: engine.cfg(),
                state: engine.state(),
                tex: engine.tex(),
                subagent_depth: 0,
            };
            if let Err(e) =
                crate::agent::pipeline::channel_actions::send_channel_message(&cctx, &g.channel, chat_id, &body).await
            {
                tracing::debug!(session = %g.session_id, channel = %g.channel, error = %e,
                    "goal-interrupted channel-push failed (UI bell still delivered)");
            }
        }
        if let Err(e) = crate::db::session_goals::set_status(&db, g.session_id, "paused").await {
            tracing::warn!(session = %g.session_id, error = %e, "goal-interrupted pause failed");
        }
        state.infra.metrics.record_redrive_event(&g.agent_id, "interactive_goal_notified");
        notified += 1;
    }
    tracing::info!(notified, total = goals.len(), "interrupted interactive goals notified");
}

/// Load OPEX_MASTER_KEY (or legacy OPEX_MASTER_KEY) from environment or auto-generate and save to .env.
fn get_master_key() -> String {
    match opex_gateway_util::env::env_var("MASTER_KEY") {
        Some(v) => v,
        None => {
            let mut key = [0u8; 32];
            rand::RngCore::fill_bytes(&mut rand::rng(), &mut key);
            let generated = hex::encode(key);

            // Try to append to .env automatically
            let env_path = std::path::PathBuf::from(".env");
            if let Ok(mut content) = std::fs::read_to_string(&env_path)
                && !content.contains("OPEX_MASTER_KEY") {
                    if !content.ends_with('\n') { content.push('\n'); }
                    content.push_str(&format!("OPEX_MASTER_KEY={generated}\n"));
                    if std::fs::write(&env_path, content).is_ok() {
                        eprintln!("[dotenv] OPEX_MASTER_KEY auto-generated and saved to .env");
                    }
                }

            eprintln!();
            eprintln!("!!! OPEX_MASTER_KEY is not set !!!");
            eprintln!("Secrets encrypted this session will be LOST on restart.");
            eprintln!("Add this to your .env file and restart:");
            eprintln!("  OPEX_MASTER_KEY={generated}");
            eprintln!();
            tracing::error!(
                "OPEX_MASTER_KEY not set — ephemeral key in use, secrets will NOT survive restart"
            );
            generated
        }
    }
}

/// Initialize the tool registry by loading service endpoints from the workspace.
async fn init_tool_registry() -> tools::ToolRegistry {
    let service_map = tools::service_registry::load_service_map(config::WORKSPACE_DIR).await;
    let tool_registry = tools::ToolRegistry::from_config(&service_map);
    tracing::info!(tools = tool_registry.len().await, "tool registry loaded from workspace");

    // Spawn periodic health check for external tools
    let registry = tool_registry.clone();
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(std::time::Duration::from_secs(60));
        loop {
            interval.tick().await;
            registry.health_check().await;
        }
    });

    // Periodic upload cleanup (every hour, delete files older than 7 days)
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(std::time::Duration::from_secs(3600));
        loop {
            interval.tick().await;
            agent::cleanup_stale_uploads(
                config::WORKSPACE_DIR,
                std::time::Duration::from_secs(7 * 86400),
            ).await;
        }
    });

    tool_registry
}

/// Initialize the Container Manager for Docker-based MCP servers.
///
/// `shutdown` is passed so the idle-reaper task (Bug 14) can select on it and exit
/// promptly on graceful shutdown.
async fn init_container_manager(
    shutdown: tokio_util::sync::CancellationToken,
) -> Option<Arc<containers::ContainerManager>> {
    let docker_url = std::env::var("DOCKER_HOST")
        .unwrap_or_else(|_| "unix:///var/run/docker.sock".to_string());
    let mcp_map = crate::tools::mcp_workspace::load_mcp_map(crate::config::MCP_DIR).await;
    tracing::info!(count = mcp_map.len(), dir = crate::config::MCP_DIR, "loaded MCP configs from workspace");

    match containers::ContainerManager::new(&docker_url, mcp_map.clone()) {
        Ok(cm) => {
            let cm = Arc::new(cm);
            // Start persistent MCP servers
            if let Err(e) = cm.start_persistent().await {
                tracing::warn!(error = %e, "failed to start some persistent MCP MCP servers");
            }
            // Cleanup orphaned on-demand containers from previous crash
            cm.cleanup_orphans().await;
            // Spawn idle reaper (Bug 14: cancelled on shutdown via the passed token).
            let cm_clone = cm.clone();
            let reaper_cancel = shutdown.clone();
            tokio::spawn(async move {
                let mut interval = tokio::time::interval(std::time::Duration::from_secs(30));
                loop {
                    tokio::select! {
                        biased;
                        _ = reaper_cancel.cancelled() => break,
                        _ = interval.tick() => {}
                    }
                    cm_clone.reap_idle().await;
                }
            });
            Some(cm)
        }
        Err(e) => {
            tracing::warn!(error = %e, "Docker not available, MCP disabled");
            None
        }
    }
}

/// Initialize the MCP registry and discover tools from persistent and always-on servers.
async fn init_mcp_registry(container_manager: Option<Arc<containers::ContainerManager>>) -> Option<Arc<mcp::McpRegistry>> {
    let mcp_map = crate::tools::mcp_workspace::load_mcp_map(crate::config::MCP_DIR).await;
    let cache_dir = std::path::Path::new(crate::config::MCP_DIR).join(".cache");

    // Canonicalize workspace and (optionally) the deploy source tree so the MCP
    // path rewriter can translate host paths to container mounts.
    let workspace_dir = std::fs::canonicalize(crate::config::WORKSPACE_DIR)
        .unwrap_or_else(|_| std::path::PathBuf::from(crate::config::WORKSPACE_DIR));
    let source_dir = std::env::current_dir()
        .ok()
        .and_then(|cwd| {
            // `opex-src` is typically a sibling of the runtime directory.
            let src = cwd.parent()?.join("opex-src");
            if src.is_dir() { Some(src) } else { None }
        })
        .or_else(|| {
            // Fallback: look for a directory named `opex-src` in the parent of
            // the (canonicalized) workspace dir. Using the canonical path
            // matters — `WORKSPACE_DIR` is a relative literal ("workspace"),
            // whose `.parent()` is the empty string and would resolve `opex-src`
            // against the process cwd instead of the runtime root.
            let src = workspace_dir.parent()?.join("opex-src");
            if src.is_dir() { Some(src) } else { None }
        });

    // Always create the registry — URL-based MCPs work without Docker.
    // `source_mount_dir` is `None` when detection failed — path rewriting for
    // `/src` is then disabled rather than silently redirecting to `/workspace`.
    let has_docker = container_manager.is_some();
    let registry = Arc::new(mcp::McpRegistry::with_optional_source_dir(
        container_manager,
        cache_dir,
        workspace_dir,
        source_dir,
    ));
    tracing::info!(has_docker, mcp_count = mcp_map.len(), "MCP registry initialized");

    // Load on-demand tool definitions from the file cache so the LLM sees them
    // immediately after a core restart — without starting any Docker container.
    let enabled_mcps: std::collections::HashSet<String> = mcp_map.keys().cloned().collect();
    match registry.load_cached_tools_from_disk(&enabled_mcps).await {
        Ok(count) => tracing::info!(count, "loaded MCP tool cache from disk"),
        Err(e) => tracing::warn!(error = %e, "failed to load MCP tool cache from disk"),
    }

    // Discover tools from persistent and always-on MCP servers at startup.
    for (name, entry) in &mcp_map {
        if entry.mode == "persistent" || entry.mode == "always-on" {
            match registry.discover_tools(name).await {
                Ok(tools) => tracing::info!(
                    mcp = %name, mode = %entry.mode, tools = tools.len(),
                    "discovered MCP tools"
                ),
                Err(e) => tracing::warn!(
                    mcp = %name, mode = %entry.mode, error = %e,
                    "failed to discover MCP tools"
                ),
            }
        }
    }

    Some(registry)
}

/// Spawn various background tasks for session cleanup, watchdog, and health monitoring.
///
/// `shutdown` is cancelled when the server begins graceful shutdown. Each loop
/// selects on `shutdown.cancelled()` so it exits within one tick rather than
/// completing its current DB round-trip (Bug 24).
async fn spawn_background_tasks(
    state: &gateway::AppState,
    process_manager: Option<Arc<process_manager::ProcessManager>>,
    agent_configs: &[config::AgentConfig],
    shutdown: tokio_util::sync::CancellationToken,
) {
    // Periodic session agent pool cleanup (every 5 minutes)
    let pools = state.agents.session_pools.clone();
    let shutdown_pools = shutdown.clone();
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(std::time::Duration::from_secs(300));
        loop {
            tokio::select! {
                biased;
                _ = shutdown_pools.cancelled() => break,
                _ = interval.tick() => {}
            }
            agent::session_agent_pool::cleanup_stale_pools(&pools).await;
        }
    });

    // Stream cleanup: in-memory broadcast (2 min TTL) + DB jobs (1 hour TTL)
    let registry = state.channels.stream_registry.clone();
    let cleanup_db = state.infra.db.clone();
    let shutdown_stream = shutdown.clone();
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(std::time::Duration::from_secs(300));
        loop {
            tokio::select! {
                biased;
                _ = shutdown_stream.cancelled() => break,
                _ = interval.tick() => {}
            }
            registry.cleanup(std::time::Duration::from_secs(120)).await;
            gateway::stream_jobs::cleanup_old_jobs(&cleanup_db).await.ok();
        }
    });

    // Last-resort safety-net: any session still 'running' with idle beyond
    // 3× max per-agent threshold is force-finalized.
    let max_per_agent_secs: i64 = agent_configs.iter()
        .filter_map(|c| c.agent.watchdog.as_ref())
        .map(|w| w.inactivity_secs as i64)
        .max()
        .unwrap_or(600);
    let safety_net = max_per_agent_secs.saturating_mul(3);
    match crate::db::sessions::finalize_truly_stale_sessions(&state.infra.db, safety_net).await {
        Ok(0) => {}
        Ok(n) => tracing::warn!(forced = n, threshold_secs = safety_net,
            "startup safety-net force-marked stale 'running' sessions"),
        Err(e) => tracing::error!(error = %e, "safety-net query failed"),
    }

    // Watchdog: detect and kill sessions stuck in 'running'
    let watchdog_db = state.infra.db.clone();
    let watchdog_registry = state.channels.stream_registry.clone();
    let watchdog_ui_tx = state.channels.ui_event_tx.clone();
    use std::collections::HashMap;
    let agent_inactivity: HashMap<String, i64> = agent_configs.iter()
        .map(|c| (
            c.agent.name.clone(),
            c.agent.watchdog.as_ref()
                .map(|w| w.inactivity_secs as i64)
                .unwrap_or(600),
        ))
        .collect();
    let shutdown_watchdog = shutdown.clone();
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(std::time::Duration::from_secs(60));
        loop {
            tokio::select! {
                biased;
                _ = shutdown_watchdog.cancelled() => break,
                _ = interval.tick() => {}
            }
            match crate::db::sessions::find_stale_running_sessions_per_agent(
                &watchdog_db,
                &agent_inactivity,
                600,
            ).await {
                Ok(stale) if stale.is_empty() => {}
                Ok(stale) => {
                    tracing::warn!(count = stale.len(),
                        "watchdog: found {} stale running session(s)", stale.len());
                    for (session_id, agent_id, idle_secs) in stale {
                        tracing::warn!(%session_id, %agent_id, idle_secs,
                            "watchdog: terminating stale session");
                        watchdog_registry.cancel(&session_id.to_string()).await;
                        let reason = format!("watchdog_inactivity_{idle_secs}s");
                        match crate::db::sessions::cleanup_session_terminated(
                            &watchdog_db, session_id, "timeout", &reason,
                        ).await {
                            Ok(true) => {
                                notify_session_timeout(
                                    &watchdog_db,
                                    &watchdog_ui_tx,
                                    &agent_id,
                                    session_id,
                                    idle_secs,
                                ).await;
                            }
                            Ok(false) => tracing::debug!(%session_id,
                                "watchdog cleanup: session already terminal"),
                            Err(e) => tracing::error!(error = %e, %session_id,
                                "watchdog cleanup failed"),
                        }
                    }
                }
                Err(e) => tracing::error!(error = %e, "watchdog query failed"),
            }
        }
    });

    // Channel health monitor
    let health_channels = state.channels.connected_channels.clone();
    let health_pm = process_manager;
    let shutdown_file = shutdown.clone();
    let shutdown_health = shutdown;
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(std::time::Duration::from_secs(120));
        loop {
            tokio::select! {
                biased;
                _ = shutdown_health.cancelled() => break,
                _ = interval.tick() => {}
            }
            let now = chrono::Utc::now();
            let stale_threshold = chrono::Duration::minutes(5);
            let channels = health_channels.read().await;
            let mut needs_restart = false;
            for ch in channels.iter() {
                if now - ch.last_activity > stale_threshold {
                    tracing::warn!(agent = %ch.agent_name, channel = %ch.channel_type, "stale channel adapter detected");
                    needs_restart = true;
                }
            }
            drop(channels);
            if needs_restart && let Some(ref pm) = health_pm {
                pm.restart("channels").await.ok();
            }
        }
    });

    // File Handler Hub: universal async-handler worker (handler_jobs queue).
    crate::agent::file_handler_worker::spawn_file_handler_worker(state, shutdown_file);
}

/// Start all agents defined in the configuration.
async fn start_configured_agents(state: &gateway::AppState, agent_configs: &[config::AgentConfig]) {
    for agent_cfg in agent_configs {
        match gateway::start_agent_from_config(
            agent_cfg,
            &state.agents,
            &state.infra,
            &state.auth,
            &state.channels,
            &state.config,
            &state.status,
            &state.handlers,
        ).await {
            Ok((handle, guard)) => {
                let name = agent_cfg.agent.name.clone();
                state.agents.map.write().await.insert(name.clone(), handle);
                if let Some(guard) = guard {
                    state.auth.access_guards.write().await.insert(name.clone(), guard);
                }
                // Ensure sandbox
                if !agent_cfg.agent.base && let Some(ref sb) = state.infra.sandbox {
                    let deps = state.agents.deps.read().await;
                    if let Ok(host_path) = std::fs::canonicalize(&deps.workspace_dir) {
                        sb.ensure_container(&name, &host_path.to_string_lossy(), false, Some(&state.auth.oauth)).await.ok();
                    }
                }
            }
            Err(e) => tracing::error!(agent = %agent_cfg.agent.name, error = %e, "failed to start agent"),
        }
    }
}

/// Schedule periodic system maintenance jobs (decay, cleanup, backup).
async fn schedule_periodic_jobs(
    state: &gateway::AppState,
    agent_configs: &[config::AgentConfig],
) -> anyhow::Result<()> {
    use anyhow::Context as _;

    let sched = &state.agents.scheduler;
    let db = &state.infra.db;

    // Load dynamic cron jobs
    let engines = state.agents.get_engines_map().await;
    if let Err(e) = sched.load_dynamic_jobs(db, &engines).await {
        tracing::warn!(error = %e, "failed to load dynamic cron jobs");
    }

    // Daily maintenance jobs
    if let Err(e) = sched.add_memory_decay(db.clone()).await {
        tracing::warn!(error = %e, job = "memory_decay", "failed to register cron job");
    }
    if let Err(e) = sched.add_audit_cleanup(db.clone(), 30).await {
        tracing::warn!(error = %e, job = "audit_cleanup", "failed to register cron job");
    }
    if let Err(e) = sched.add_tool_audit_cleanup(db.clone(), 90).await {
        tracing::warn!(error = %e, job = "tool_audit_cleanup", "failed to register cron job");
    }
    if let Err(e) = sched.add_outbound_queue_cleanup(db.clone()).await {
        tracing::warn!(error = %e, job = "outbound_queue_cleanup", "failed to register cron job");
    }
    if let Err(e) = sched.add_usage_log_cleanup(db.clone()).await {
        tracing::warn!(error = %e, job = "usage_log_cleanup", "failed to register cron job");
    }
    if let Err(e) = sched.add_memory_decay_cleanup(db.clone()).await {
        tracing::warn!(error = %e, job = "memory_decay_cleanup", "failed to register cron job");
    }
    if let Err(e) = sched.add_notifications_cleanup(db.clone()).await {
        tracing::warn!(error = %e, job = "notifications_cleanup", "failed to register cron job");
    }

    // Session cleanup (based on max TTL in agent configs)
    let ttl_days = agent_configs.iter().filter_map(|c| c.agent.session.as_ref()).map(|s| s.ttl_days).max().unwrap_or(30);
    let max_sessions_per_agent = state.config.config.limits.max_sessions_per_agent;
    if let Err(e) = sched
        .add_session_cleanup(
            db.clone(),
            ttl_days,
            max_sessions_per_agent,
            state.config.config.cleanup.session_timeline_batch_size,
        )
        .await
    {
        tracing::warn!(error = %e, job = "session_cleanup", "failed to register cron job");
    }

    // One-shot enforcement of the per-agent session cap at startup. Protects
    // against cron/async-subagent backlogs that accumulated while the gateway
    // was offline; the daily cron handles steady-state growth from here on.
    if max_sessions_per_agent > 0 {
        match opex_db::sessions::cleanup_excess_sessions_per_agent(
            db,
            max_sessions_per_agent,
        ).await {
            Ok(0) => {}
            Ok(n) => tracing::info!(
                deleted = n,
                cap = max_sessions_per_agent,
                "session cap enforcement at startup trimmed excess sessions"
            ),
            Err(e) => tracing::warn!(
                error = %e,
                "session cap enforcement at startup failed (continuing)"
            ),
        }
    }

    // Phase 62 RES-03: hourly batched session_timeline cleanup. Runs
    // alongside the legacy daily add_session_cleanup (which still handles
    // cleanup_old_sessions) — the hourly job only prunes session_timeline,
    // with bounded LIMIT per batch to avoid long table locks.
    if let Err(e) = sched
        .add_session_timeline_cleanup_hourly(
            db.clone(),
            state.config.config.cleanup.session_timeline_retention_days,
            state.config.config.cleanup.session_timeline_batch_size,
        )
        .await
    {
        tracing::warn!(error = %e, job = "session_timeline_cleanup_hourly", "failed to register cron job");
    }

    // Hourly cleanup of expired uploads (tool_output + client_upload).
    // Retention is materialised at INSERT time, so no parameter needed here.
    if let Err(e) = sched.add_uploads_cleanup_hourly(db.clone()).await {
        tracing::warn!(error = %e, job = "uploads_cleanup_hourly", "failed to register cron job");
    }

    // Automatic backup
    if state.config.config.backup.enabled
        && let Err(e) = sched.add_backup(
            &state.config.config.backup.cron, state.config.config.backup.retention_days,
            state.config.config.backup.postgres_container.clone(),
            state.auth.secrets.clone(), state.agents.deps.clone(),
        ).await
    {
        tracing::error!(error = %e, "failed to schedule automatic backup");
    }

    // Skill Curator
    if state.config.config.curator.enabled
        && let Err(e) = sched.add_curator(
            &state.config.config.curator.cron,
            state.config.config.curator.clone(),
            db.clone(),
            state.agents.clone(),
        ).await {
            tracing::error!(error = %e, "failed to schedule skill curator");
        }

    sched.start().await.context("failed to start scheduler")?;
    Ok(())
}

/// Advertise the service via mDNS.
fn setup_mdns(cfg: &config::AppConfig) -> Option<mdns_sd::ServiceDaemon> {
    use mdns_sd::{ServiceDaemon, ServiceInfo};
    let port = cfg.gateway.listen.split(':').next_back().and_then(|p| p.parse().ok()).unwrap_or(18789);
    
    ServiceDaemon::new().ok().and_then(|daemon| {
        let props = [("version", env!("CARGO_PKG_VERSION"))].into_iter().map(|(k, v)| (k.to_string(), v.to_string())).collect();
        ServiceInfo::new("_opex._tcp.local.", "opex", "opex.local.", (), port, Some(props)).ok().and_then(|info| {
            daemon.register(info).ok()?;
            tracing::info!(port, "mDNS registered: opex._opex._tcp.local.");
            Some(daemon)
        })
    })
}

/// Setup Tailscale Funnel or Serve.
async fn setup_tailscale(cfg: &config::AppConfig) {
    if cfg.tailscale.enabled {
        let port = cfg.gateway.listen.split(':').next_back().unwrap_or("18789");
        let target = format!("https+insecure://localhost:{port}");
        let cmd = if cfg.tailscale.funnel { "funnel" } else { "serve" };
        tokio::process::Command::new("tailscale").args([cmd, "--bg", &target]).output().await.ok();
    }
}

/// Notify systemd that the service is ready and start watchdog ticker.
#[cfg(target_os = "linux")]
fn setup_linux_service_notify() {
    let _ = sd_notify::notify(false, &[sd_notify::NotifyState::Ready]);
    tokio::spawn(async {
        let mut interval = tokio::time::interval(std::time::Duration::from_secs(60));
        loop {
            interval.tick().await;
            let _ = sd_notify::notify(false, &[sd_notify::NotifyState::Watchdog]);
        }
    });
}

/// Setup SIGHUP handler for hot-reloading agent configs (Unix only).
/// Uses atomic-remove → cancel+drain → create → insert pattern.
/// On create failure, restores old handle so the agent remains reachable.
#[cfg(unix)]
fn setup_sighup_handler(state: gateway::AppState) {
    tokio::spawn(async move {
        use tokio::signal::unix::{signal, SignalKind};
        let mut sighup = signal(SignalKind::hangup()).expect("failed to register SIGHUP");
        loop {
            sighup.recv().await;
            tracing::info!("SIGHUP received — reloading agent configs with graceful drain");
            if let Ok(configs) = crate::config::load_agent_configs("config/agents") {
                for cfg in configs {
                    let name = cfg.agent.name.clone();

                    // 1. Atomically remove from map. During drain, the agent is absent from
                    //    the map — new requests receive "agent not found" (acceptable for the
                    //    drain window, typically < 1s for idle agents, up to 10s worst-case).
                    let old_handle = state.agents.map.write().await.remove(&name);
                    // Remove old guard now so channel adapters don't re-fetch a stale one
                    // during the creation window. Saved so we can restore it on failure.
                    let old_guard = state.auth.access_guards.write().await.remove(&name);

                    // 2. Cancel + drain on the extracted handle (write lock already released).
                    //    No race: old engine is no longer in the map, so no new request can
                    //    reach it between cancel and drain completion.
                    if let Some(ref h) = old_handle {
                        tracing::info!(agent = %name, "SIGHUP: cancelling and draining old agent");
                        h.engine.state.cancel_all_requests();
                        h.engine.state.wait_drain(std::time::Duration::from_secs(10)).await;
                    }

                    // 3. Create new engine. Guard inserted before handle (same ordering as
                    //    api_create_agent/api_update_agent) to avoid a reconnect race.
                    match crate::gateway::start_agent_from_config(
                        &cfg,
                        &state.agents,
                        &state.infra,
                        &state.auth,
                        &state.channels,
                        &state.config,
                        &state.status,
                        &state.handlers,
                    ).await {
                        Ok((new_handle, guard)) => {
                            if let Some(old) = old_handle {
                                old.shutdown(&state.agents.scheduler).await;
                            }
                            if let Some(g) = guard {
                                state.auth.access_guards.write().await.insert(name.clone(), g);
                            }
                            // old_guard is intentionally dropped here — superseded by new config.
                            state.agents.map.write().await.insert(name.clone(), new_handle);
                            tracing::info!(agent = %name, "SIGHUP: agent reloaded");
                        }
                        Err(e) => {
                            tracing::error!(agent = %name, error = %e, "SIGHUP: failed to create new engine");
                            // Restore both handle and guard so the agent remains reachable.
                            if let Some(old) = old_handle {
                                state.agents.map.write().await.insert(name.clone(), old);
                            }
                            if let Some(og) = old_guard {
                                state.auth.access_guards.write().await.insert(name.clone(), og);
                            }
                            tracing::warn!(agent = %name, "SIGHUP: restored old engine after create failure");
                        }
                    }
                }
            }
        }
    });
}

async fn shutdown_signal(hard_timeout_secs: u64) {
    let ctrl_c = async {
        tokio::signal::ctrl_c()
            .await
            .expect("failed to install Ctrl+C handler");
    };

    #[cfg(unix)]
    let terminate = async {
        tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate())
            .expect("failed to install SIGTERM handler")
            .recv()
            .await;
    };

    #[cfg(not(unix))]
    let terminate = std::future::pending::<()>();

    tokio::select! {
        () = ctrl_c => tracing::info!("received Ctrl+C"),
        () = terminate => tracing::info!("received SIGTERM"),
    }

    // Safety net: force-exit only if graceful shutdown GENUINELY hangs. This
    // budget MUST exceed the graceful path (drain_timeout_secs + managed-process
    // stop ~10s); otherwise it fires during every normal shutdown and the
    // process exits 1, making systemd log a spurious FAILURE on each restart
    // (and force-killing teardown mid-flight, which can trip the tracing span
    // registry). Caller passes `drain_timeout_secs + 20` (≈50s default).
    tokio::spawn(async move {
        tokio::time::sleep(std::time::Duration::from_secs(hard_timeout_secs)).await;
        tracing::warn!(hard_timeout_secs, "hard shutdown: graceful drain exceeded budget — forcing exit");
        std::process::exit(1);
    });
}

