-- migrations/043_messages_is_mirror.sql

-- Add is_mirror column: true = this record was written by cron delivery,
-- not generated by the LLM in a normal turn.
ALTER TABLE messages
  ADD COLUMN IF NOT EXISTS is_mirror BOOLEAN NOT NULL DEFAULT false;

-- Update the trigger that bumps sessions.last_message_at on every INSERT.
-- Mirror records should NOT push the DM session to the top of the list —
-- they are passive context records, not user-visible conversation turns.
CREATE OR REPLACE FUNCTION update_session_last_message()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.is_mirror = false THEN
    UPDATE sessions SET last_message_at = NEW.created_at WHERE id = NEW.session_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
