mod agent;
mod channels;
mod config;
mod containers;
mod db;
mod dto_export;
mod gateway;
mod memory;
mod metrics;
pub mod net;
mod oauth;
mod process_manager;
mod scheduler;
mod secrets;
mod mcp;
mod shutdown;
mod skills;
mod tasks;
mod tools;
mod uploads;

use anyhow::Result;
use std::collections::HashMap;
use std::sync::Arc;
use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt, EnvFilter};

/// Load .env file from binary's directory or current working directory.
/// In production (systemd), env vars come from `EnvironmentFile`.
fn load_env() {
    let mut env_path = std::path::PathBuf::from(".env");

    // Try from binary's directory first (most reliable for production)
    if let Ok(exe_path) = std::env::current_exe()
        && let Some(dir) = exe_path.parent() {
            let p = dir.join(".env");
            if p.exists() {
                env_path = p;
            }
        }

    // Auto-generate .env on first run (only HYDECLAW_AUTH_TOKEN and HYDECLAW_MASTER_KEY)
    if !env_path.exists() {
        let mut auth_bytes = [0u8; 32];
        let mut key_bytes = [0u8; 32];
        rand::RngCore::fill_bytes(&mut rand::rng(), &mut auth_bytes);
        rand::RngCore::fill_bytes(&mut rand::rng(), &mut key_bytes);
        let content = format!(
            "# Auto-generated by hydeclaw-core on first run\nHYDECLAW_AUTH_TOKEN={}\nHYDECLAW_MASTER_KEY={}\n",
            hex::encode(auth_bytes),
            hex::encode(key_bytes),
        );
        if std::fs::write(&env_path, &content).is_ok() {
            eprintln!("[dotenv] created .env with generated tokens: {}", env_path.display());
        }
    }

    if env_path.exists() {
        if dotenv::from_path(&env_path).is_ok() {
            eprintln!("[dotenv] loaded .env from: {}", env_path.display());
        }
    } else {
        eprintln!("[dotenv] .env not found, using environment variables");
    }
}

/// Tracing layer that broadcasts log entries as JSON to WebSocket clients.
struct BroadcastLogLayer {
    tx: tokio::sync::broadcast::Sender<String>,
}

impl<S: tracing::Subscriber> tracing_subscriber::Layer<S> for BroadcastLogLayer {
    fn on_event(&self, event: &tracing::Event<'_>, _ctx: tracing_subscriber::layer::Context<'_, S>) {
        // Skip all work when no UI clients are subscribed
        if self.tx.receiver_count() == 0 { return; }

        use tracing_subscriber::field::Visit;

        struct Visitor {
            message: String,
        }
        impl Visit for Visitor {
            fn record_debug(&mut self, field: &tracing::field::Field, value: &dyn std::fmt::Debug) {
                if field.name() == "message" {
                    self.message = format!("{value:?}");
                }
            }
        }

        let mut visitor = Visitor { message: String::new() };
        event.record(&mut visitor);

        let level = match *event.metadata().level() {
            tracing::Level::ERROR => "ERROR",
            tracing::Level::WARN => "WARN",
            tracing::Level::INFO => "INFO",
            tracing::Level::DEBUG => "DEBUG",
            tracing::Level::TRACE => "DEBUG",
        };

        let json = serde_json::json!({
            "type": "log",
            "level": level,
            "target": event.metadata().target(),
            "message": visitor.message,
            "timestamp": chrono::Utc::now().to_rfc3339(),
        });

        // Best-effort send — drop if no subscribers
        self.tx.send(json.to_string()).ok();
    }
}

/// Phase 65 OBS-01 / OBS-02 (Plan 02): live OTel provider handles retained
/// across the lifetime of the process so `main()` can invoke `.shutdown()`
/// on clean exit. OTel 0.31 removed the global `shutdown_tracer_provider()`
/// helper — providers now own their shutdown lifecycle.
#[cfg(feature = "otel")]
static OTEL_PROVIDERS: std::sync::OnceLock<(
    opentelemetry_sdk::trace::SdkTracerProvider,
    opentelemetry_sdk::metrics::SdkMeterProvider,
)> = std::sync::OnceLock::new();

/// Initialize tracing subscriber with optional OTEL layer.
///
/// Phase 65 Plan 02 (OTel 0.31 migration):
///   * `opentelemetry_sdk::trace::TracerProvider` → `SdkTracerProvider`
///   * `opentelemetry_sdk::Resource::new(...)` → `Resource::builder().with_service_name(...).build()`
///   * `SpanExporter::builder().with_tonic()` now requires the `grpc-tonic`
///     feature (enabled at workspace level).
///   * `shutdown_tracer_provider()` removed — caller owns the handle and
///     invokes `.shutdown()` on exit. Handles stored in `OTEL_PROVIDERS`.
///   * Metrics provider now created alongside tracer so Plan 02 OTel
///     instruments (`tool_latency_seconds`, `llm_call_duration_seconds`,
///     `db_query_duration_seconds`, `llm_tokens_total`) are exported via
///     the same OTLP collector endpoint.
fn init_tracing(log_tx: tokio::sync::broadcast::Sender<String>, cfg: &config::AppConfig) {
    let env_filter = EnvFilter::try_from_default_env().unwrap_or_else(|_| "hydeclaw_core=info".into());
    let fmt_layer = tracing_subscriber::fmt::layer();
    let broadcast_layer = BroadcastLogLayer { tx: log_tx };

    #[cfg(feature = "otel")]
    {
        use opentelemetry_otlp::WithExportConfig;

        if cfg.otel.enabled {
            let endpoint = std::env::var("OTEL_EXPORTER_OTLP_ENDPOINT")
                .unwrap_or_else(|_| "http://localhost:4317".to_string());
            eprintln!(
                "[otel] exporting traces + metrics to {endpoint} as {:?}",
                cfg.otel.service_name
            );

            // Shared resource: `service.name` identifies this process in the
            // collector. `Resource::builder()` pulls default attributes
            // (service.version via env, telemetry.sdk.*) — the 0.31 idiom.
            let resource = opentelemetry_sdk::Resource::builder()
                .with_service_name(cfg.otel.service_name.clone())
                .build();

            // ── Trace exporter + provider ───────────────────────────────
            let span_exporter = match opentelemetry_otlp::SpanExporter::builder()
                .with_tonic()
                .with_endpoint(&endpoint)
                .build()
            {
                Ok(e) => e,
                Err(err) => {
                    eprintln!("[otel] span exporter build failed: {err}; falling back");
                    tracing_subscriber::registry()
                        .with(env_filter)
                        .with(fmt_layer)
                        .with(broadcast_layer)
                        .init();
                    return;
                }
            };
            let tracer_provider = opentelemetry_sdk::trace::SdkTracerProvider::builder()
                .with_batch_exporter(span_exporter)
                .with_resource(resource.clone())
                .build();
            opentelemetry::global::set_tracer_provider(tracer_provider.clone());

            // ── Metric exporter + provider (Plan 02 OBS-02) ─────────────
            let metric_exporter = match opentelemetry_otlp::MetricExporter::builder()
                .with_tonic()
                .with_endpoint(&endpoint)
                .build()
            {
                Ok(e) => e,
                Err(err) => {
                    eprintln!("[otel] metric exporter build failed: {err}; proceeding with traces only");
                    // Keep tracer provider wired; install empty meter
                    // provider so `MetricsRegistry::install_otel_instruments`
                    // fails safe (the underlying global meter is a no-op).
                    let _ = OTEL_PROVIDERS.set((
                        tracer_provider.clone(),
                        opentelemetry_sdk::metrics::SdkMeterProvider::builder().build(),
                    ));
                    let tracer = opentelemetry::trace::TracerProvider::tracer(
                        &tracer_provider,
                        "hydeclaw",
                    );
                    let otel_layer = tracing_opentelemetry::layer().with_tracer(tracer);
                    tracing_subscriber::registry()
                        .with(env_filter)
                        .with(fmt_layer)
                        .with(broadcast_layer)
                        .with(otel_layer)
                        .init();
                    return;
                }
            };
            let meter_provider = opentelemetry_sdk::metrics::SdkMeterProvider::builder()
                .with_periodic_exporter(metric_exporter)
                .with_resource(resource)
                .build();
            opentelemetry::global::set_meter_provider(meter_provider.clone());

            // Retain handles for graceful shutdown.
            let _ = OTEL_PROVIDERS.set((tracer_provider.clone(), meter_provider));

            let tracer = opentelemetry::trace::TracerProvider::tracer(&tracer_provider, "hydeclaw");
            let otel_layer = tracing_opentelemetry::layer().with_tracer(tracer);

            tracing_subscriber::registry()
                .with(env_filter)
                .with(fmt_layer)
                .with(broadcast_layer)
                .with(otel_layer)
                .init();
            return;
        }
    }

    #[cfg(not(feature = "otel"))]
    let _ = &cfg.otel; // suppress unused warning

    tracing_subscriber::registry()
        .with(env_filter)
        .with(fmt_layer)
        .with(broadcast_layer)
        .init();
}

#[tokio::main(worker_threads = 4)]
async fn main() -> Result<()> {
    // Load .env file (no-op if not found - env vars may come from systemd EnvironmentFile)
    load_env();

    // Load config BEFORE tracing init (OTEL layer depends on config)
    let cfg = config::AppConfig::load("config/hydeclaw.toml")?;

    // Broadcast channel for real-time log streaming (created before tracing init)
    let (log_tx, _) = tokio::sync::broadcast::channel::<String>(256);

    // Structured logging with broadcast layer for UI + optional OTEL
    init_tracing(log_tx.clone(), &cfg);

    tracing::info!(listen = %cfg.gateway.listen, "HydeClaw Core starting...");

    // systemd unit installation is handled by setup.sh (see "Systemd service"
    // stage). Core no longer writes unit files at runtime — that was a
    // hot-path side effect that belonged to the installer.

    // Config hot-reload watcher
    let shared_config = std::sync::Arc::new(tokio::sync::RwLock::new(cfg.clone()));
    let config_api_write_flag = std::sync::Arc::new(std::sync::atomic::AtomicBool::new(false));
    config::spawn_config_watcher("config/hydeclaw.toml".to_string(), shared_config.clone(), config_api_write_flag.clone());

    // Database pool — DATABASE_URL env var overrides hydeclaw.toml value
    let db_url = std::env::var("DATABASE_URL").unwrap_or_else(|_| cfg.database.url.clone());
    let db_pool = db::create_pool(&db_url).await?;
    tracing::info!("database connected, running migrations...");
    sqlx::migrate::Migrator::new(std::path::Path::new("migrations"))
        .await?
        .run(&db_pool)
        .await?;
    tracing::info!("migrations complete");

    // Startup cleanup: repair sessions interrupted by previous crash (batched)
    cleanup_interrupted_sessions(&db_pool).await;

    // Secrets vault
    let master_key_hex = get_master_key();
    let secrets_manager = secrets::SecretsManager::new(&master_key_hex, db_pool.clone())?;
    let secrets_count = secrets_manager.load_all().await?;

    // One-time migration: move channel credentials from JSONB to encrypted vault.
    // Idempotent — safe to run every startup.
    gateway::migrate_credentials_to_vault(&db_pool, &secrets_manager).await;
    // One-time migration: copy provider keys from legacy vault patterns into unified PROVIDER_CREDENTIALS.
    gateway::migrate_provider_keys_to_vault(&db_pool, &secrets_manager).await;
    // One-time migration: move OAuth tokens/credentials from old per-agent format to per-account vault.
    if let Err(e) = crate::oauth::migrate_oauth_vault(&db_pool, &secrets_manager).await {
        tracing::error!(error = %e, "OAuth vault migration failed — old tokens may not be available");
    }

    // No hardcoded secrets — user creates all secrets via UI.
    // Channel-specific secrets (bot tokens) are auto-seeded when agents are created.
    // HYDECLAW_AUTH_TOKEN and HYDECLAW_MASTER_KEY stay in .env only (bootstrap).

    let secrets_manager = Arc::new(secrets_manager);
    tracing::info!(count = secrets_count, "secrets vault loaded");

    // Memory store (embedding via toolgate proxy)
    let toolgate_url = cfg.toolgate_url.clone().unwrap_or_else(|| "http://localhost:9011".to_string());
    let effective_toolgate_url = if cfg.memory.enabled { &toolgate_url } else { "" };
    let embedder: Arc<dyn memory::EmbeddingService> = Arc::new(memory::ToolgateEmbedder::new(
        db_pool.clone(),
        effective_toolgate_url,
        cfg.memory.embed_dim.unwrap_or(0),
        cfg.memory.embed_dimensions.unwrap_or(0),
    ));
    // FTS language resolution order: TOML override → persisted DB value → "simple" placeholder
    // (auto-detect runs later after agent_configs is loaded). Persisted value comes
    // from `system_flags` so PUT /api/memory/fts-language survives restarts.
    let fts_lang = if let Some(toml_lang) = cfg.memory.fts_language.clone() {
        toml_lang
    } else {
        sqlx::query_scalar::<_, serde_json::Value>(
            "SELECT value FROM system_flags WHERE key = 'memory.fts_language'",
        )
        .fetch_optional(&db_pool)
        .await
        .ok()
        .flatten()
        .and_then(|v| v.as_str().map(String::from))
        .unwrap_or_else(|| "simple".to_string())
    };
    let memory_store = Arc::new(memory::MemoryStore::new(db_pool.clone(), embedder.clone(), fts_lang));
    if embedder.is_available() {
        tracing::info!("embedding configured — will initialize on first memory operation");
        // Watch workspace files for auto-reindexing
        memory::spawn_workspace_watcher(
            config::WORKSPACE_DIR.to_string(),
            memory_store.clone(),
            tokio::runtime::Handle::current(),
        );
        // First-run bootstrap: the watcher only handles file CHANGE events, so
        // a fresh install with workspace files already on disk would have zero
        // shared chunks until someone manually triggers `memory.reindex`. If
        // we see no shared chunks at all, enqueue a one-shot reindex task —
        // the memory worker picks it up and indexes the workspace (idempotent
        // via DELETE-by-source + INSERT). Subsequent restarts skip the check.
        //
        // Run in a background task that waits for toolgate (managed child
        // process spawned later in main) to come up. Without this delay the
        // worker would dequeue immediately and fail every embedding call with
        // a connection error, marking the task as 'done' with 0 indexed.
        let bootstrap_pool = db_pool.clone();
        let bootstrap_toolgate_url = toolgate_url.clone();
        tokio::spawn(async move {
            // Wait up to 90s for toolgate to be ready (POST /health 200).
            let http = reqwest::Client::builder()
                .timeout(std::time::Duration::from_secs(3))
                .build()
                .expect("reqwest client build");
            let health_url = format!(
                "{}/health",
                bootstrap_toolgate_url.trim_end_matches('/')
            );
            let mut ready = false;
            for attempt in 1..=18 {
                tokio::time::sleep(std::time::Duration::from_secs(5)).await;
                if http.get(&health_url).send().await.is_ok_and(|r| r.status().is_success()) {
                    tracing::info!(attempt, "memory bootstrap: toolgate ready");
                    ready = true;
                    break;
                }
            }
            if !ready {
                tracing::warn!(
                    "memory bootstrap: toolgate not reachable after 90s — skipping reindex enqueue"
                );
                return;
            }

            let has_shared: bool = match sqlx::query_scalar::<_, bool>(
                "SELECT EXISTS(SELECT 1 FROM memory_chunks WHERE scope = 'shared')",
            )
            .fetch_one(&bootstrap_pool)
            .await
            {
                Ok(v) => {
                    tracing::info!(has_shared = v, "memory bootstrap check");
                    v
                }
                Err(e) => {
                    tracing::warn!(
                        error = %e,
                        "memory bootstrap probe failed — assuming shared chunks present"
                    );
                    true
                }
            };
            if !has_shared {
                match db::memory_queries::enqueue_reindex_task(
                    &bootstrap_pool,
                    serde_json::json!({"agent_id": "", "include_sessions": false}),
                )
                .await
                {
                    Ok(task_id) => tracing::info!(
                        %task_id,
                        "no shared chunks — enqueued initial workspace reindex"
                    ),
                    Err(e) => tracing::warn!(
                        error = %e,
                        "failed to enqueue initial workspace reindex"
                    ),
                }
            }
        });
    } else {
        tracing::info!("embedding not configured — memory features disabled");
    }

    // Tool registry — load service endpoints from workspace/tools/*.yaml
    let tool_registry = init_tool_registry().await;

    // Container Manager (Docker lifecycle for on-demand MCP servers)
    let container_manager = init_container_manager().await;

    // MCP registry (MCP tool discovery from MCP containers)
    let mcp_registry = init_mcp_registry(container_manager.clone()).await;

    // Load agent configs — no default agent created; Setup Wizard handles first agent
    std::fs::create_dir_all("config/agents")?;
    let mut agent_configs = config::load_agent_configs("config/agents")?;
    if agent_configs.is_empty() {
        tracing::info!("no agent configs found — Setup Wizard will create the first agent");
    }
    tracing::info!(agents = agent_configs.len(), "agent configs loaded");

    // Migrate legacy inline-routing TOMLs → `connection = "<name>"` references
    // (Tasks 20 + 21 — atomic write, backup, per-agent marker, crash recovery).
    // Runs once at startup after DB migrations and before agent engines spawn.
    {
        let providers_snapshot = crate::db::providers::list_providers(&db_pool)
            .await
            .unwrap_or_else(|e| {
                tracing::warn!(error = %e, "providers list failed; TOML migrator will see empty DB");
                Vec::new()
            });
        let agents_dir = std::path::PathBuf::from("config/agents");
        let migrator = crate::agent::toml_migrator::TomlMigrator {
            config_dir: &agents_dir,
            db_providers: &providers_snapshot,
        };
        migrator
            .migrate_all()
            .await
            .map_err(|e| anyhow::anyhow!("TOML routing migration failed: {e}"))?;
    }

    // Issue E: the TOML migrator above may have rewritten agent TOMLs on disk
    // (e.g. hoisting legacy inline-routing into `connection = "<name>"`). The
    // `agent_configs` we loaded at the start of this block predates those
    // rewrites, so every engine spawned from it would consume unmigrated data
    // until the next restart. Re-read the configs now that both migrators have
    // settled the on-disk representation.
    agent_configs = config::load_agent_configs("config/agents")?;
    tracing::info!(
        agents = agent_configs.len(),
        "agent configs re-loaded after TOML migration"
    );

    // Auto-detect FTS language from first agent's language ONLY when neither
    // TOML override nor persisted DB value is present (i.e. memory_store is
    // currently using the "simple" placeholder). On detect, persist to DB so
    // future restarts skip the agent-order-dependent detection.
    if cfg.memory.fts_language.is_none()
        && memory_store.fts_language() == "simple"
        && let Some(first) = agent_configs.first() {
            let detected = memory::admin::detect_fts_language(&first.agent.language);
            tracing::info!(
                agent = %first.agent.name,
                agent_lang = %first.agent.language,
                fts_lang = %detected,
                "auto-detected FTS language from first agent"
            );
            memory_store.set_fts_language(&detected);
            if let Err(e) = sqlx::query(
                "INSERT INTO system_flags (key, value) \
                 VALUES ('memory.fts_language', $1::jsonb) \
                 ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now()",
            )
            .bind(serde_json::Value::String(detected.clone()))
            .execute(&db_pool)
            .await
            {
                tracing::warn!(error = %e, "failed to persist auto-detected FTS language");
            }
        }

    // UI event broadcast channel (shared between scheduler and WS handler)
    let (ui_event_tx, _) = tokio::sync::broadcast::channel::<String>(512);

    // Scheduler
    let sched = Arc::new(scheduler::Scheduler::new(ui_event_tx.clone()).await?);

    // Extract shared URLs from service configs
    let service_map = tools::service_registry::load_service_map(config::WORKSPACE_DIR).await;
    let toolgate_url = cfg.toolgate_url.clone()
        .or_else(|| service_map.get("toolgate").map(|t| t.url.clone()));

    // Code execution sandbox (optional — requires Docker + sandbox.enabled = true)
    let tool_embed_cache = Arc::new(tools::embedding::ToolEmbeddingCache::new());

    let docker_url = std::env::var("DOCKER_HOST")
        .unwrap_or_else(|_| "tcp://127.0.0.1:2375".to_string());

    let sandbox = if cfg.sandbox.enabled {
        match containers::sandbox::CodeSandbox::new(&docker_url, &cfg.sandbox) {
            Ok(s) => {
                tracing::info!(
                    image = %cfg.sandbox.image,
                    timeout = cfg.sandbox.timeout_secs,
                    "code execution sandbox initialized"
                );
                Some(Arc::new(s))
            }
            Err(e) => {
                tracing::warn!(error = %e, "failed to initialize sandbox, code_exec disabled");
                None
            }
        }
    } else {
        tracing::info!("sandbox disabled (sandbox.enabled = false)");
        None
    };

    // Shared agent dependencies (for hot-starting agents from API)
    let penalty_cache = Arc::new(crate::db::tool_quality::PenaltyCache::new(db_pool.clone()));

    let audit_queue = Arc::new(crate::db::audit_queue::AuditQueue::new(db_pool.clone()));

    let agent_deps = Arc::new(tokio::sync::RwLock::new(gateway::AgentDeps {
        mcp: mcp_registry.clone(),
        workspace_dir: config::WORKSPACE_DIR.to_string(),
        toolgate_url,
        sandbox: sandbox.clone(),
        tool_embed_cache,
        penalty_cache: penalty_cache.clone(),
        audit_queue,
    }));

    // Build running agent handles + access guards
    let agents_map: gateway::AgentMap = Arc::new(tokio::sync::RwLock::new(HashMap::new()));
    let guards_map: gateway::AccessGuardMap = Arc::new(tokio::sync::RwLock::new(HashMap::new()));

    // Stream registry for SSE resume support
    let stream_registry = Arc::new(gateway::stream_registry::StreamRegistry::new(db_pool.clone()));

    // Managed process manager (channels, toolgate — native child processes)
    let base_dir = std::env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from("."));
    let process_manager: Option<Arc<process_manager::ProcessManager>> = if cfg.managed_process.is_empty() {
        None
    } else {
        let pm = Arc::new(process_manager::ProcessManager::new(cfg.managed_process.clone(), base_dir));
        tracing::info!(count = cfg.managed_process.len(), "managed process manager initialized");
        Some(pm)
    };

    // OAuth manager
    let public_url = cfg.gateway.public_url.clone().unwrap_or_else(|| {
        // Extract port from listen address (e.g. "0.0.0.0:18789" → 18789)
        let port = cfg.gateway.listen.rsplit(':').next().unwrap_or("18789");
        format!("http://localhost:{port}")
    });
    let oauth_manager = Arc::new(crate::oauth::OAuthManager::new(
        db_pool.clone(),
        secrets_manager.clone(),
        reqwest::Client::new(),
        public_url,
    ));

    // Phase 62 RES-02: single process-wide metrics registry. Shared via
    // `InfraServices.metrics` so SSE coalescer (Plan 03) and
    // `/api/health/dashboard` handler (Plan 02) see the same counters.
    let metrics = Arc::new(crate::metrics::MetricsRegistry::new());

    // LLM-timeout refactor Task 22: publish the shared registry to the
    // process-wide OnceLock so `RoutingProvider::handle_provider_error`
    // (which has no `AppState` in scope) can bump llm_timeout_total and
    // llm_failover_total against the same Arc as the dashboard handler.
    crate::metrics::install_global(metrics.clone());

    // Phase 65 Plan 02 OBS-02: when --features otel is on, wire OTel
    // instruments onto the registry. Safe to call unconditionally — the
    // method is itself feature-gated and `install_otel_instruments()` is a
    // no-op if the global MeterProvider was not set by init_tracing (e.g.
    // when `cfg.otel.enabled = false`). Idempotent via `OnceLock::set`.
    #[cfg(feature = "otel")]
    metrics.install_otel_instruments();

    let bg_tasks = Arc::new(tokio_util::task::TaskTracker::new());

    // Shared application state for gateway (built early so start_agent_from_config can use it)
    let state = gateway::AppState {
        agents: gateway::clusters::AgentCore::new(
            agents_map.clone(),
            agent_deps,
            Arc::new(tokio::sync::RwLock::new(std::collections::HashMap::new())),
            tool_registry.clone(),
            sched.clone(),
        ),
        auth: gateway::clusters::AuthServices::new(
            secrets_manager.clone(),
            guards_map.clone(),
            oauth_manager,
            Arc::new(tokio::sync::Mutex::new(std::collections::HashMap::new())),
        ),
        infra: gateway::clusters::InfraServices::new(
            db_pool.clone(),
            memory_store,
            embedder.clone(),
            container_manager.clone(),
            sandbox.clone(),
            process_manager.clone(),
            metrics.clone(),
            secrets_manager.clone(),
        ),
        channels: gateway::clusters::ChannelBus::new(
            Arc::new(tokio::sync::RwLock::new(Vec::new())),
            log_tx.clone(),
            ui_event_tx.clone(),
            stream_registry.clone(),
            bg_tasks.clone(),
        ),
        config: gateway::clusters::ConfigServices::new(
            cfg.clone(),
            shared_config.clone(),
            Arc::new(tokio::sync::Mutex::new(())),
            config_api_write_flag.clone(),
        ),
        status: gateway::clusters::StatusMonitor::new(
            Arc::new(std::sync::RwLock::new(std::collections::HashMap::new())),
            Arc::new(crate::gateway::state::PollingDiagnostics::new()),
            Arc::new(tokio::sync::RwLock::new(None)),
            std::time::Instant::now(),
        ),
    };

    // Managed processes started after TcpListener::bind below — toolgate needs Core API ready.

    // Spawn periodic background tasks (cleanup, watchdog, etc.)
    spawn_background_tasks(&state, process_manager.clone(), &agent_configs).await;

    // Start all agents from config
    start_configured_agents(&state, &agent_configs).await;

    // Load dynamic cron jobs and schedule periodic system jobs
    schedule_periodic_jobs(&state, &agent_configs).await;

    // Background task: renew expiring Gmail watches every 6 hours
    {
        let renewal_db = db_pool.clone();
        let renewal_oauth = state.auth.oauth.clone();
        tokio::spawn(async move {
            let mut interval = tokio::time::interval(std::time::Duration::from_secs(6 * 3600));
            loop {
                interval.tick().await;
                crate::gateway::renew_expiring_gmail_watches(&renewal_db, &renewal_oauth).await;
            }
        });
    }

    // Start gateway (blocks until shutdown signal)
    let listener = tokio::net::TcpListener::bind(&cfg.gateway.listen).await?;
    tracing::info!(addr = %cfg.gateway.listen, "gateway listening");

    // ── mDNS: advertise _hydeclaw._tcp.local. ──
    let _mdns_daemon = setup_mdns(&cfg);

    // Tailscale Funnel setup
    setup_tailscale(&cfg).await;

    // Notify systemd: service is ready (no-op on non-Linux)
    #[cfg(target_os = "linux")]
    setup_linux_service_notify();

    // SIGHUP: hot-restart agents (Unix only)
    #[cfg(unix)]
    setup_sighup_handler(state.clone());

    // Start managed child processes just before serve
    if let Some(ref pm) = process_manager {
        let pm_clone = pm.clone();
        tokio::spawn(async move {
            tokio::time::sleep(std::time::Duration::from_millis(500)).await;
            pm_clone.start_all().await;
        });
    }

    let shutdown_bg_tasks = state.channels.bg_tasks.clone();
    axum::serve(listener, gateway::router(state)?.into_make_service_with_connect_info::<std::net::SocketAddr>())
        .with_graceful_shutdown(shutdown_signal())
        .await?;

    // ── Graceful shutdown: cancel → drain → stop ──────────────────────────
    // Phase 62 RES-05: extracted into `shutdown::drain_agents_with_scheduler`.
    // Fixes v0.18.0 lock-during-drain bug (read lock held across wait_drain
    // await). Drain timeout is configurable via [shutdown] drain_timeout_secs
    // in hydeclaw.toml (default 30s); systemd TimeoutStopSec should be
    // drain_timeout_secs + 10s buffer (40s) so SIGKILL never races the drain.
    let drain_timeout = std::time::Duration::from_secs(cfg.shutdown.drain_timeout_secs);
    crate::shutdown::drain_agents_with_scheduler(
        agents_map.clone(),
        drain_timeout,
        &sched,
    ).await;

    // Drain background tasks spawned by finalize (notifications, knowledge extraction).
    // close() prevents new spawns; timeout prevents hanging on unresponsive DB.
    shutdown_bg_tasks.close();
    let _ = tokio::time::timeout(
        std::time::Duration::from_secs(5),
        shutdown_bg_tasks.wait(),
    ).await;

    tracing::info!("graceful shutdown: stopping managed processes");
    if let Some(pm) = &process_manager { pm.stop_all().await; }

    #[cfg(target_os = "linux")]
    let _ = sd_notify::notify(false, &[sd_notify::NotifyState::Stopping]);

    // Phase 65 OBS-01 (Plan 02): OTel 0.31 removed the global
    // `shutdown_tracer_provider()` helper — each provider owns its own
    // shutdown. Invoke both the tracer and the metric provider so any
    // in-flight OTLP batches are flushed before the process exits.
    #[cfg(feature = "otel")]
    if cfg.otel.enabled
        && let Some((tracer_provider, meter_provider)) = OTEL_PROVIDERS.get()
    {
        if let Err(err) = tracer_provider.shutdown() {
            tracing::warn!(error = %err, "otel tracer provider shutdown failed");
        }
        if let Err(err) = meter_provider.shutdown() {
            tracing::warn!(error = %err, "otel meter provider shutdown failed");
        }
    }

    tracing::info!("HydeClaw Core shutting down");
    Ok(())
}

/// Repair sessions interrupted by previous crash (batched loop).
async fn cleanup_interrupted_sessions(db_pool: &sqlx::PgPool) {
    loop {
        match crate::db::sessions::cleanup_interrupted_sessions(db_pool).await {
            Ok(0) => {
                tracing::info!("startup cleanup: no more interrupted sessions");
                break;
            }
            Ok(cleaned) => {
                tracing::info!(cleaned, "cleanup batch completed, checking for more");
            }
            Err(e) => {
                tracing::error!(error = %e, "startup cleanup failed (non-fatal)");
                break;
            }
        }
    }
}

/// Load HYDECLAW_MASTER_KEY from environment or auto-generate and save to .env.
fn get_master_key() -> String {
    std::env::var("HYDECLAW_MASTER_KEY").unwrap_or_else(|_| {
        let mut key = [0u8; 32];
        rand::RngCore::fill_bytes(&mut rand::rng(), &mut key);
        let generated = hex::encode(key);
        
        // Try to append to .env automatically
        let env_path = std::path::PathBuf::from(".env");
        if let Ok(mut content) = std::fs::read_to_string(&env_path)
            && !content.contains("HYDECLAW_MASTER_KEY") {
                if !content.ends_with('\n') { content.push('\n'); }
                content.push_str(&format!("HYDECLAW_MASTER_KEY={generated}\n"));
                if std::fs::write(&env_path, content).is_ok() {
                    eprintln!("[dotenv] HYDECLAW_MASTER_KEY auto-generated and saved to .env");
                }
            }

        eprintln!();
        eprintln!("!!! HYDECLAW_MASTER_KEY is not set !!!");
        eprintln!("Secrets encrypted this session will be LOST on restart.");
        eprintln!("Add this to your .env file and restart:");
        eprintln!("  HYDECLAW_MASTER_KEY={generated}");
        eprintln!();
        tracing::error!(
            "HYDECLAW_MASTER_KEY not set — ephemeral key in use, secrets will NOT survive restart"
        );
        generated
    })
}

/// Initialize the tool registry by loading service endpoints from the workspace.
async fn init_tool_registry() -> tools::ToolRegistry {
    let service_map = tools::service_registry::load_service_map(config::WORKSPACE_DIR).await;
    let tool_registry = tools::ToolRegistry::from_config(&service_map);
    tracing::info!(tools = tool_registry.len().await, "tool registry loaded from workspace");

    // Spawn periodic health check for external tools
    let registry = tool_registry.clone();
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(std::time::Duration::from_secs(60));
        loop {
            interval.tick().await;
            registry.health_check().await;
        }
    });

    // Periodic upload cleanup (every hour, delete files older than 7 days)
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(std::time::Duration::from_secs(3600));
        loop {
            interval.tick().await;
            agent::cleanup_stale_uploads(
                config::WORKSPACE_DIR,
                std::time::Duration::from_secs(7 * 86400),
            ).await;
        }
    });

    tool_registry
}

/// Initialize the Container Manager for Docker-based MCP servers.
async fn init_container_manager() -> Option<Arc<containers::ContainerManager>> {
    let docker_url = std::env::var("DOCKER_HOST")
        .unwrap_or_else(|_| "tcp://127.0.0.1:2375".to_string());
    let mcp_map = crate::tools::mcp_workspace::load_mcp_map(crate::config::MCP_DIR).await;
    tracing::info!(count = mcp_map.len(), dir = crate::config::MCP_DIR, "loaded MCP configs from workspace");

    match containers::ContainerManager::new(&docker_url, mcp_map.clone()) {
        Ok(cm) => {
            let cm = Arc::new(cm);
            // Start persistent MCP servers
            if let Err(e) = cm.start_persistent().await {
                tracing::warn!(error = %e, "failed to start some persistent MCP MCP servers");
            }
            // Cleanup orphaned on-demand containers from previous crash
            cm.cleanup_orphans().await;
            // Spawn idle reaper
            let cm_clone = cm.clone();
            tokio::spawn(async move {
                let mut interval = tokio::time::interval(std::time::Duration::from_secs(30));
                loop {
                    interval.tick().await;
                    cm_clone.reap_idle().await;
                }
            });
            Some(cm)
        }
        Err(e) => {
            tracing::warn!(error = %e, "Docker not available, MCP disabled");
            None
        }
    }
}

/// Initialize the MCP registry and discover tools from persistent servers.
async fn init_mcp_registry(container_manager: Option<Arc<containers::ContainerManager>>) -> Option<Arc<mcp::McpRegistry>> {
    let mcp_map = crate::tools::mcp_workspace::load_mcp_map(crate::config::MCP_DIR).await;
    let mcp_registry = container_manager.map(|cm| {
        let sr = mcp::McpRegistry::new(cm);
        Arc::new(sr)
    });

    // Discover tools from persistent MCP servers
    if let Some(ref sr) = mcp_registry {
        for (name, entry) in &mcp_map {
            if entry.mode == "persistent" {
                match sr.discover_tools(name).await {
                    Ok(tools) => {
                        tracing::info!(mcp = %name, tools = tools.len(), "discovered MCP tools");
                    }
                    Err(e) => {
                        tracing::warn!(mcp = %name, error = %e, "failed to discover MCP tools");
                    }
                }
            }
        }
    }
    mcp_registry
}

/// Spawn various background tasks for session cleanup, watchdog, and health monitoring.
async fn spawn_background_tasks(
    state: &gateway::AppState,
    process_manager: Option<Arc<process_manager::ProcessManager>>,
    agent_configs: &[config::AgentConfig],
) {
    // Periodic session agent pool cleanup (every 5 minutes)
    let pools = state.agents.session_pools.clone();
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(std::time::Duration::from_secs(300));
        loop {
            interval.tick().await;
            agent::session_agent_pool::cleanup_stale_pools(&pools).await;
        }
    });

    // Stream cleanup: in-memory broadcast (2 min TTL) + DB jobs (1 hour TTL)
    let registry = state.channels.stream_registry.clone();
    let cleanup_db = state.infra.db.clone();
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(std::time::Duration::from_secs(300));
        loop {
            interval.tick().await;
            registry.cleanup(std::time::Duration::from_secs(120)).await;
            gateway::stream_jobs::cleanup_old_jobs(&cleanup_db).await.ok();
        }
    });

    // Watchdog: detect and kill sessions stuck in 'running'
    let watchdog_db = state.infra.db.clone();
    let watchdog_registry = state.channels.stream_registry.clone();
    let inactivity_secs = agent_configs
        .iter()
        .filter_map(|c| c.agent.watchdog.as_ref())
        .map(|w| w.inactivity_secs)
        .min()
        .unwrap_or(600);
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(std::time::Duration::from_secs(60));
        loop {
            interval.tick().await;
            match crate::db::sessions::find_stale_running_sessions(&watchdog_db, inactivity_secs).await {
                Ok(stale) if stale.is_empty() => {}
                Ok(stale) => {
                    tracing::warn!(count = stale.len(), "watchdog: found {} stale running session(s)", stale.len());
                    for (session_id, agent_id) in stale {
                        tracing::warn!(%session_id, %agent_id, "watchdog: killing stale session");
                        watchdog_registry.cancel(&session_id.to_string()).await;
                        sqlx::query("DELETE FROM messages WHERE session_id = $1 AND status = 'streaming'")
                            .bind(session_id).execute(&watchdog_db).await.ok();
                        crate::db::sessions::insert_synthetic_tool_results(&watchdog_db, session_id).await.ok();
                        crate::db::sessions::set_session_run_status(&watchdog_db, session_id, "timeout").await.ok();
                    }
                }
                Err(e) => tracing::error!(error = %e, "watchdog query failed"),
            }
        }
    });

    // Channel health monitor
    let health_channels = state.channels.connected_channels.clone();
    let health_pm = process_manager;
    tokio::spawn(async move {
        let mut interval = tokio::time::interval(std::time::Duration::from_secs(120));
        loop {
            interval.tick().await;
            let now = chrono::Utc::now();
            let stale_threshold = chrono::Duration::minutes(5);
            let channels = health_channels.read().await;
            let mut needs_restart = false;
            for ch in channels.iter() {
                if now - ch.last_activity > stale_threshold {
                    tracing::warn!(agent = %ch.agent_name, channel = %ch.channel_type, "stale channel adapter detected");
                    needs_restart = true;
                }
            }
            drop(channels);
            if needs_restart && let Some(ref pm) = health_pm {
                pm.restart("channels").await.ok();
            }
        }
    });
}

/// Start all agents defined in the configuration.
async fn start_configured_agents(state: &gateway::AppState, agent_configs: &[config::AgentConfig]) {
    for agent_cfg in agent_configs {
        match gateway::start_agent_from_config(
            agent_cfg,
            &state.agents,
            &state.infra,
            &state.auth,
            &state.channels,
            &state.config,
            &state.status,
        ).await {
            Ok((handle, guard)) => {
                let name = agent_cfg.agent.name.clone();
                state.agents.map.write().await.insert(name.clone(), handle);
                if let Some(guard) = guard {
                    state.auth.access_guards.write().await.insert(name.clone(), guard);
                }
                // Ensure sandbox
                if !agent_cfg.agent.base && let Some(ref sb) = state.infra.sandbox {
                    let deps = state.agents.deps.read().await;
                    if let Ok(host_path) = std::fs::canonicalize(&deps.workspace_dir) {
                        sb.ensure_container(&name, &host_path.to_string_lossy(), false, Some(&state.auth.oauth)).await.ok();
                    }
                }
            }
            Err(e) => tracing::error!(agent = %agent_cfg.agent.name, error = %e, "failed to start agent"),
        }
    }
}

/// Schedule periodic system maintenance jobs (decay, cleanup, backup).
async fn schedule_periodic_jobs(state: &gateway::AppState, agent_configs: &[config::AgentConfig]) {
    let sched = &state.agents.scheduler;
    let db = &state.infra.db;

    // Load dynamic cron jobs
    let engines = state.agents.get_engines_map().await;
    sched.load_dynamic_jobs(db, &engines).await.ok();

    // Daily maintenance jobs
    sched.add_memory_decay(db.clone()).await.ok();
    sched.add_task_cleanup(db.clone()).await.ok();
    sched.add_audit_cleanup(db.clone(), 30).await.ok();
    sched.add_tool_audit_cleanup(db.clone(), 90).await.ok();
    sched.add_pending_messages_cleanup(db.clone()).await.ok();
    sched.add_outbound_queue_cleanup(db.clone()).await.ok();
    sched.add_usage_log_cleanup(db.clone()).await.ok();
    sched.add_memory_decay_cleanup(db.clone()).await.ok();
    sched.add_notifications_cleanup(db.clone()).await.ok();

    // Session cleanup (based on max TTL in agent configs)
    let ttl_days = agent_configs.iter().filter_map(|c| c.agent.session.as_ref()).map(|s| s.ttl_days).max().unwrap_or(30);
    let max_sessions_per_agent = state.config.config.limits.max_sessions_per_agent;
    sched
        .add_session_cleanup(
            db.clone(),
            ttl_days,
            max_sessions_per_agent,
            state.config.config.cleanup.session_events_batch_size,
        )
        .await
        .ok();

    // One-shot enforcement of the per-agent session cap at startup. Protects
    // against cron/async-subagent backlogs that accumulated while the gateway
    // was offline; the daily cron handles steady-state growth from here on.
    if max_sessions_per_agent > 0 {
        match hydeclaw_db::sessions::cleanup_excess_sessions_per_agent(
            db,
            max_sessions_per_agent,
        ).await {
            Ok(0) => {}
            Ok(n) => tracing::info!(
                deleted = n,
                cap = max_sessions_per_agent,
                "session cap enforcement at startup trimmed excess sessions"
            ),
            Err(e) => tracing::warn!(
                error = %e,
                "session cap enforcement at startup failed (continuing)"
            ),
        }
    }

    // Phase 62 RES-03: hourly batched session_events WAL cleanup. Runs
    // alongside the legacy daily add_session_cleanup (which still handles
    // cleanup_old_sessions) — the hourly job only prunes session_events,
    // with bounded LIMIT per batch to avoid long table locks.
    sched
        .add_session_events_cleanup_hourly(
            db.clone(),
            state.config.config.cleanup.session_events_retention_days,
            state.config.config.cleanup.session_events_batch_size,
        )
        .await
        .ok();

    // Automatic backup
    if state.config.config.backup.enabled
        && let Err(e) = sched.add_backup(
            &state.config.config.backup.cron, state.config.config.backup.retention_days,
            state.config.config.backup.postgres_container.clone(),
            state.auth.secrets.clone(), state.agents.deps.clone(),
        ).await
    {
        tracing::error!(error = %e, "failed to schedule automatic backup");
    }

    sched.start().await.ok();
}

/// Advertise the service via mDNS.
fn setup_mdns(cfg: &config::AppConfig) -> Option<mdns_sd::ServiceDaemon> {
    use mdns_sd::{ServiceDaemon, ServiceInfo};
    let port = cfg.gateway.listen.split(':').next_back().and_then(|p| p.parse().ok()).unwrap_or(18789);
    
    ServiceDaemon::new().ok().and_then(|daemon| {
        let props = [("version", env!("CARGO_PKG_VERSION"))].into_iter().map(|(k, v)| (k.to_string(), v.to_string())).collect();
        ServiceInfo::new("_hydeclaw._tcp.local.", "hydeclaw", "hydeclaw.local.", (), port, Some(props)).ok().and_then(|info| {
            daemon.register(info).ok()?;
            tracing::info!(port, "mDNS registered: hydeclaw._hydeclaw._tcp.local.");
            Some(daemon)
        })
    })
}

/// Setup Tailscale Funnel or Serve.
async fn setup_tailscale(cfg: &config::AppConfig) {
    if cfg.tailscale.enabled {
        let port = cfg.gateway.listen.split(':').next_back().unwrap_or("18789");
        let target = format!("https+insecure://localhost:{port}");
        let cmd = if cfg.tailscale.funnel { "funnel" } else { "serve" };
        tokio::process::Command::new("tailscale").args([cmd, "--bg", &target]).output().await.ok();
    }
}

/// Notify systemd that the service is ready and start watchdog ticker.
#[cfg(target_os = "linux")]
fn setup_linux_service_notify() {
    let _ = sd_notify::notify(false, &[sd_notify::NotifyState::Ready]);
    tokio::spawn(async {
        let mut interval = tokio::time::interval(std::time::Duration::from_secs(60));
        loop {
            interval.tick().await;
            let _ = sd_notify::notify(false, &[sd_notify::NotifyState::Watchdog]);
        }
    });
}

/// Setup SIGHUP handler for hot-reloading agent configs (Unix only).
/// Uses atomic-remove → cancel+drain → create → insert pattern.
/// On create failure, restores old handle so the agent remains reachable.
#[cfg(unix)]
fn setup_sighup_handler(state: gateway::AppState) {
    tokio::spawn(async move {
        use tokio::signal::unix::{signal, SignalKind};
        let mut sighup = signal(SignalKind::hangup()).expect("failed to register SIGHUP");
        loop {
            sighup.recv().await;
            tracing::info!("SIGHUP received — reloading agent configs with graceful drain");
            if let Ok(configs) = crate::config::load_agent_configs("config/agents") {
                for cfg in configs {
                    let name = cfg.agent.name.clone();

                    // 1. Atomically remove from map. During drain, the agent is absent from
                    //    the map — new requests receive "agent not found" (acceptable for the
                    //    drain window, typically < 1s for idle agents, up to 10s worst-case).
                    let old_handle = state.agents.map.write().await.remove(&name);

                    // 2. Cancel + drain on the extracted handle (write lock already released).
                    //    No race: old engine is no longer in the map, so no new request can
                    //    reach it between cancel and drain completion.
                    if let Some(ref h) = old_handle {
                        tracing::info!(agent = %name, "SIGHUP: cancelling and draining old agent");
                        h.engine.state.cancel_all_requests();
                        h.engine.state.wait_drain(std::time::Duration::from_secs(10)).await;
                    }

                    // 3. Create new engine, insert into map, then shut down old engine cleanly.
                    match crate::gateway::start_agent_from_config(
                        &cfg,
                        &state.agents,
                        &state.infra,
                        &state.auth,
                        &state.channels,
                        &state.config,
                        &state.status,
                    ).await {
                        Ok((new_handle, guard)) => {
                            if let Some(old) = old_handle {
                                old.shutdown(&state.agents.scheduler).await;
                            }
                            state.agents.map.write().await.insert(name.clone(), new_handle);
                            if let Some(g) = guard {
                                state.auth.access_guards.write().await.insert(name.clone(), g);
                            }
                            tracing::info!(agent = %name, "SIGHUP: agent reloaded");
                        }
                        Err(e) => {
                            tracing::error!(agent = %name, error = %e, "SIGHUP: failed to create new engine");
                            // Restore old handle if new engine failed to start, so the agent
                            // is not permanently absent from the map.
                            if let Some(old) = old_handle {
                                state.agents.map.write().await.insert(name.clone(), old);
                                tracing::warn!(agent = %name, "SIGHUP: restored old engine after create failure");
                            }
                        }
                    }
                }
            }
        }
    });
}

async fn shutdown_signal() {
    let ctrl_c = async {
        tokio::signal::ctrl_c()
            .await
            .expect("failed to install Ctrl+C handler");
    };

    #[cfg(unix)]
    let terminate = async {
        tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate())
            .expect("failed to install SIGTERM handler")
            .recv()
            .await;
    };

    #[cfg(not(unix))]
    let terminate = std::future::pending::<()>();

    tokio::select! {
        () = ctrl_c => tracing::info!("received Ctrl+C"),
        () = terminate => tracing::info!("received SIGTERM"),
    }

    // Safety net: force-exit after 15s if graceful shutdown hangs
    tokio::spawn(async {
        tokio::time::sleep(std::time::Duration::from_secs(15)).await;
        tracing::warn!("hard shutdown: 15s timeout exceeded");
        std::process::exit(1);
    });
}

