use axum::{
    Router,
    extract::State,
    http::StatusCode,
    response::IntoResponse,
    routing::get,
    Json,
};
use serde_json::json;

use crate::db::file_scenarios;
use crate::gateway::AppState;
use crate::gateway::clusters::InfraServices;

pub(crate) fn routes() -> Router<AppState> {
    Router::new()
        .route("/api/file-scenarios", get(api_list_file_scenarios))
}

pub(crate) async fn api_list_file_scenarios(
    State(infra): State<InfraServices>,
) -> impl IntoResponse {
    match file_scenarios::list(&infra.db).await {
        Ok(rows) => (StatusCode::OK, Json(json!({ "scenarios": rows }))).into_response(),
        Err(e) => (
            StatusCode::INTERNAL_SERVER_ERROR,
            Json(json!({ "error": e.to_string() })),
        )
            .into_response(),
    }
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    #[sqlx::test(migrations = "../../migrations")]
    async fn list_returns_seeded_and_inserted_rows(pool: sqlx::PgPool) {
        // Insert one binding directly (Phase-1 schema columns; id is not
        // auto-generated by the DB so we supply gen_random_uuid()).
        sqlx::query(
            "INSERT INTO file_scenarios \
             (id, match_type, executor, action_ref, label, is_default, priority, enabled, scope, created_by) \
             VALUES (gen_random_uuid(),'image/*','tool','describe','Describe image',true,100,true,'global','ui')",
        )
        .execute(&pool)
        .await
        .unwrap();

        let rows = crate::db::file_scenarios::list(&pool).await.unwrap();
        assert!(
            rows.iter().any(|r| r.match_type == "image/*" && r.action_ref == "describe"),
            "inserted image/* describe binding must be listed: {rows:?}"
        );
    }
}
